# -*- coding: utf-8 -*-
"""Textos bilingues (pt-BR / es-419) del informe de diagnostico APP / RL / vegetacao nativa.

TXT[clave] = {"pt": ..., "es": ...}. Los valores pueden ser str (con placeholders {nombre}
que an_05_informe.py rellena con las cifras formateadas de resultados_analisis.json) o listas
de str (bullets / filas). Todos los glifos son WinAnsi (Helvetica): sin <=, >=, flechas ni
subindices Unicode. Markup ReportLab permitido: <b>, <i>, <br/>, &amp;.
"""

TXT = {
    # ------------------------------------------------------------- portada ----
    'cover_title': {'pt': 'Diagnóstico de APP, Reserva Legal e Vegetação Nativa',
                    'es': 'Diagnóstico de APP, Reserva Legal y Vegetación Nativa'},
    'cover_sub': {'pt': 'Fazenda Santo Antônio · São Sebastião da Amoreira – PR · Sentinel-2 29/08/2026',
                  'es': 'Fazenda Santo Antônio · São Sebastião da Amoreira – PR · Sentinel-2 29/08/2026'},
    'footer': {'pt': 'Fazenda Santo Antônio · APP / RL · 09/2026',
               'es': 'Fazenda Santo Antônio · APP / RL · 09/2026'},
    'ficha_h': {'pt': 'Ficha técnica', 'es': 'Ficha técnica'},
    'ficha': {'pt': [
        ['Cliente', 'Sonia Maria Bigati'],
        ['Imóvel', 'Fazenda Santo Antônio — {imovel_ha} ha em 2 polígonos ({pol1} + {pol2} ha)'],
        ['Município', 'São Sebastião da Amoreira – PR (IBGE 4126009), Norte Pioneiro'],
        ['Módulo fiscal', '{mf} ha (INCRA) — {n_mf} MF: média propriedade (mais de 4 e até 10 MF)'],
        ['Bioma', 'Mata Atlântica (IBGE 2024); Floresta Estacional Semidecidual provável, a confirmar'],
        ['CRS', 'SIRGAS 2000 / UTM 22S (EPSG:31982); entrega em SIRGAS 2000 geográfico (EPSG:4674)'],
        ['Cena satelital', 'Sentinel-2C L2A, {escena_data} ({escena_id}), 100% livre de nuvens sobre o imóvel'],
        ['Data de emissão', '06/09/2026'],
        ['Responsável técnico', 'Eng. Agr. Nilton Camargo, Director Técnico — Pixadvisor Agricultura de Precisão<br/>nilton.camargo@pixadvisor.network · +591 721 49171'],
    ], 'es': [
        ['Cliente', 'Sonia Maria Bigati'],
        ['Inmueble', 'Fazenda Santo Antônio — {imovel_ha} ha en 2 polígonos ({pol1} + {pol2} ha)'],
        ['Municipio', 'São Sebastião da Amoreira – PR (IBGE 4126009), Norte Pioneiro'],
        ['Módulo fiscal', '{mf} ha (INCRA) — {n_mf} MF: "média propriedade" (más de 4 y hasta 10 MF)'],
        ['Bioma', 'Mata Atlántica (IBGE 2024); Floresta Estacional Semidecidual probable, a confirmar'],
        ['CRS', 'SIRGAS 2000 / UTM 22S (EPSG:31982); entrega en SIRGAS 2000 geográfico (EPSG:4674)'],
        ['Escena satelital', 'Sentinel-2C L2A, {escena_data} ({escena_id}), 100% libre de nubes sobre el inmueble'],
        ['Fecha de emisión', '06/09/2026'],
        ['Responsable técnico', 'Ing. Agr. Nilton Camargo, Director Técnico — Pixadvisor Agricultura de Precisión<br/>nilton.camargo@pixadvisor.network · +591 721 49171'],
    ]},
    'linha_lbl': {'pt': 'Em uma linha', 'es': 'En una línea'},
    'linha': {'pt': 'A APP exigível do imóvel é de {app_ha} ha, {pct_conf}% já coberta por vegetação nativa; faltam recompor {app_rec} ha (ou {cenB} ha pela faixa reduzida do PRA-PR) e a Reserva Legal de {rl_ex} ha tem déficit de {rl_def_com} ha mesmo computando a APP vegetada. Diagnóstico preliminar por satélite: leito regular, nascentes e estágio sucessional exigem confirmação em campo.',
              'es': 'La APP exigible del inmueble es de {app_ha} ha, {pct_conf}% ya cubierta por vegetación nativa; faltan recomponer {app_rec} ha (o {cenB} ha por la faja reducida del PRA-PR) y la Reserva Legal de {rl_ex} ha tiene un déficit de {rl_def_com} ha aun computando la APP vegetada. Diagnóstico preliminar por satélite: el "leito regular", las nascentes y el estadio sucesional exigen confirmación en campo.'},
    'toc_h': {'pt': 'Índice', 'es': 'Índice'},

    # ------------------------------------------------------- resumo executivo ----
    'resumo_h': {'pt': 'Resumo executivo', 'es': 'Resumen ejecutivo'},
    'kpi': {'pt': [['{app_ha} ha', 'APP exigível<br/>[{app_min}; {app_max}]'], ['{pct_conf}%', 'APP conforme<br/>({app_veg} ha vegetada)'],
                   ['{app_rec} ha', 'a recompor (cenário A)<br/>{cenB} ha no PRA-PR'], ['{rl_ex} ha', 'Reserva Legal exigida<br/>(20% de {imovel_ha} ha)'],
                   ['{rl_disp_com} ha', 'RL disponível<br/>(com APP, art. 15)'], ['{rl_def_com} ha', 'déficit de RL<br/>(conservador: {rl_cons_def} ha)']],
            'es': [['{app_ha} ha', 'APP exigible<br/>[{app_min}; {app_max}]'], ['{pct_conf}%', 'APP conforme<br/>({app_veg} ha vegetada)'],
                   ['{app_rec} ha', 'a recomponer (escenario A)<br/>{cenB} ha en PRA-PR'], ['{rl_ex} ha', 'Reserva Legal exigida<br/>(20% de {imovel_ha} ha)'],
                   ['{rl_disp_com} ha', 'RL disponible<br/>(con APP, art. 15)'], ['{rl_def_com} ha', 'déficit de RL<br/>(conservador: {rl_cons_def} ha)']]},
    'achados_h': {'pt': 'Principais achados', 'es': 'Principales hallazgos'},
    'achados': {'pt': [
        '<b>Hidrografia.</b> {km_fbds} km de cursos d\'água FBDS/IAT (até 10 m de largura) cruzam o imóvel, mais 1 nascente FBDS e 2 reservatórios artificiais por barramento. A rede derivada do DEM coincide com a FBDS a 10,8 m (mediana); o regime perene só está confirmado em {km_perene} km (IBGE BC250).',
        '<b>Vegetação nativa.</b> A classificação Random Forest a 10 m (OA {oa}, kappa {kappa}) mapeia {flor_rf} ha de floresta nativa no imóvel (faixa de incerteza {flor_min}–{flor_max} ha), o triplo do que registram MapBiomas 2025 ({mb_ff} ha) e FBDS 2013 ({fbds_ff} ha), porque resolve a faixa ciliar jovem do norte (fragmento 13, {f13_ha} ha).',
        '<b>APP.</b> Dos {app_ha} ha exigíveis (30 m dos cursos + 50 m da nascente), {app_veg} ha estão vegetados, {app_agua} ha são espelho d\'água e {app_rec} ha precisam de recomposição ({app_silv} ha deles com silvicultura). A floresta dentro da mesma APP passou de {floresta2013} ha (FBDS 2013) para {app_veg} ha (2026).',
        '<b>Área consolidada.</b> {consol} ha da APP sem vegetação eram uso antrópico em 2008 (MapBiomas): elegíveis ao art. 61-A. Com a faixa de 20 m / raio 15 m da Lei PR 18.295/2014 (imóvel de 4–10 MF), a recomposição cai para {cenB} ha — condicionada a CAR inscrito até 31/12/2023 e adesão ao PRA.',
        '<b>Reserva Legal.</b> Exigência de {rl_ex} ha; remanescente fora da APP {rl_rem} ha; com a APP vegetada (art. 15) o disponível chega a {rl_disp_com} ha e o déficit a {rl_def_com} ha. A proposta de localização ({rl_prop} ha) soma remanescente, APP e um corredor de recomposição de {rl_corr} ha contíguo à mata ciliar.',
    ], 'es': [
        '<b>Hidrografía.</b> {km_fbds} km de cursos de agua FBDS/IAT (hasta 10 m de ancho) cruzan el inmueble, más 1 nascente FBDS y 2 reservorios artificiales por represamiento. La red derivada del DEM coincide con la FBDS a 10,8 m (mediana); el régimen perenne solo está confirmado en {km_perene} km (IBGE BC250).',
        '<b>Vegetación nativa.</b> La clasificación Random Forest a 10 m (OA {oa}, kappa {kappa}) mapea {flor_rf} ha de floresta nativa en el inmueble (banda de incertidumbre {flor_min}–{flor_max} ha), el triple de lo que registran MapBiomas 2025 ({mb_ff} ha) y FBDS 2013 ({fbds_ff} ha), porque resuelve la faja ribereña joven del norte (fragmento 13, {f13_ha} ha).',
        '<b>APP.</b> De las {app_ha} ha exigibles (30 m de los cursos + 50 m de la nascente), {app_veg} ha están vegetadas, {app_agua} ha son espejo de agua y {app_rec} ha necesitan recomposición ({app_silv} ha de ellas con silvicultura). La floresta dentro de la misma APP pasó de {floresta2013} ha (FBDS 2013) a {app_veg} ha (2026).',
        '<b>Área consolidada.</b> {consol} ha de la APP sin vegetación eran uso antrópico en 2008 (MapBiomas): elegibles al art. 61-A. Con la faja de 20 m / radio 15 m de la Ley PR 18.295/2014 (inmueble de 4–10 MF), la recomposición baja a {cenB} ha — condicionada a CAR inscrito hasta 31/12/2023 y adhesión al PRA.',
        '<b>Reserva Legal.</b> Exigencia de {rl_ex} ha; remanente fuera de la APP {rl_rem} ha; con la APP vegetada (art. 15) el disponible llega a {rl_disp_com} ha y el déficit a {rl_def_com} ha. La propuesta de localización ({rl_prop} ha) suma remanente, APP y un corredor de recomposición de {rl_corr} ha contiguo al bosque ribereño.',
    ]},
    'reco_lbl': {'pt': 'Recomendação', 'es': 'Recomendación'},
    'reco': {'pt': 'Antes de qualquer protocolo no SICAR-PR: (1) levantar com GPS RTK a borda do leito regular e as nascentes na estação seca; (2) conferir a data de inscrição do CAR (define se vale o cenário B de {cenB} ha ou o A de {app_rec} ha); (3) inventário florestal CONAMA 2/1994 nos três fragmentos; (4) só então protocolar o mapa CAR deste diagnóstico e o plano de recomposição da APP e da RL.',
             'es': 'Antes de cualquier trámite en el SICAR-PR: (1) levantar con GPS RTK el borde del "leito regular" y las nascentes en estación seca; (2) verificar la fecha de inscripción del CAR (define si rige el escenario B de {cenB} ha o el A de {app_rec} ha); (3) inventario forestal CONAMA 2/1994 en los tres fragmentos; (4) recién entonces protocolar el mapa CAR de este diagnóstico y el plan de recomposición de la APP y de la RL.'},

    # ------------------------------------------------------------ sec 1 legal ----
    's1_h': {'pt': 'Base legal aplicável', 'es': 'Base legal aplicable'},
    's1_intro': {'pt': 'O diagnóstico aplica a Lei 12.651/2012 (Código Florestal, texto compilado), a Lei Estadual PR 18.295/2014 (PRA-PR) e as normas do CAR/SICAR. Os termos jurídicos são usados no original: <i>Área de Preservação Permanente</i> (APP), <i>Reserva Legal</i> (RL), <i>área rural consolidada</i> e <i>leito regular</i>.',
                 'es': 'El diagnóstico aplica la Ley 12.651/2012 (Código Forestal brasileño, texto compilado), la Ley Estadual PR 18.295/2014 (PRA-PR) y las normas del CAR/SICAR. Los términos jurídicos se mantienen en portugués: <i>Área de Preservação Permanente</i> (APP), <i>Reserva Legal</i> (RL), <i>área rural consolidada</i> (uso agropecuario anterior al 22/07/2008) y <i>leito regular</i> (cauce ordinario).'},
    's1_t1_h': {'pt': 'Faixas de APP hídrica — art. 4º da Lei 12.651/2012', 'es': 'Fajas de APP hídrica — art. 4º de la Ley 12.651/2012'},
    's1_t1': {'pt': [['Feição (art. 4º)', 'Faixa mínima', 'Aplicação neste imóvel'],
                     ['I-a  Curso d\'água natural de menos de 10 m (perene ou intermitente; efêmeros excluídos)', '30 m desde a borda da calha do leito regular', 'Sim: {km_fbds} km de cursos FBDS "até 10 m"; largura de campo não medida'],
                     ['I-b  Curso de 10 a 50 m', '50 m', 'Não identificado dentro do imóvel'],
                     ['II-a  Lago ou lagoa natural, zona rural', '100 m (50 m se até 20 ha)', 'Não há lago natural'],
                     ['III  Reservatório artificial por barramento de curso natural', 'faixa definida na licença ambiental; §4º dispensa se menor que 1 ha', 'Dois reservatórios (FBDS 19083 e 20452): faixa "a definir pelo IAT"'],
                     ['IV  Nascente ou olho d\'água (perene; STF ADI 4903: também intermitente)', 'raio 50 m', '1 nascente FBDS; 2 candidatos DEM a validar'],
                     ['V, IX, X  Encosta maior que 45º, topo de morro, altitude maior que 1.800 m', '—', 'Não aplicável ao relevo do imóvel (não avaliado por não haver indícios)']],
              'es': [['Elemento (art. 4º)', 'Faja mínima', 'Aplicación en este inmueble'],
                     ['I-a  Curso de agua natural de menos de 10 m (perenne o intermitente; efímeros excluidos)', '30 m desde el borde del cauce del "leito regular"', 'Sí: {km_fbds} km de cursos FBDS "hasta 10 m"; ancho de campo no medido'],
                     ['I-b  Curso de 10 a 50 m', '50 m', 'No identificado dentro del inmueble'],
                     ['II-a  Lago o laguna natural, zona rural', '100 m (50 m si hasta 20 ha)', 'No hay lago natural'],
                     ['III  Reservorio artificial por represamiento de curso natural', 'faja definida en la licencia ambiental; §4º dispensa si menor que 1 ha', 'Dos reservorios (FBDS 19083 y 20452): faja "a definir por el IAT"'],
                     ['IV  Nascente u "olho d\'água" (perenne; STF ADI 4903: también intermitente)', 'radio 50 m', '1 nascente FBDS; 2 candidatos DEM a validar'],
                     ['V, IX, X  Ladera mayor que 45º, cima de cerro, altitud mayor que 1.800 m', '—', 'No aplicable al relieve del inmueble (no evaluado por no haber indicios)']]},
    's1_t2_h': {'pt': 'Reserva Legal, área consolidada e regularização', 'es': 'Reserva Legal, área consolidada y regularización'},
    's1_t2': {'pt': [['Dispositivo', 'Regra', 'Efeito para a Fazenda Santo Antônio'],
                     ['Art. 12, II', 'RL de 20% do imóvel fora da Amazônia Legal', '0,20 x {imovel_ha} ha = <b>{rl_ex} ha</b> (servidões administrativas assumidas em 0 ha — IN MMA 2/2014 art. 23)'],
                     ['Art. 15', 'APP computa na RL se: (I) não implicar nova conversão; (II) estiver conservada ou em recuperação; (III) o imóvel estiver no CAR', 'APP vegetada de {app_veg} ha somada ao remanescente: disponível {rl_disp_com} ha'],
                     ['Art. 14', 'Localização da RL: corredores com APP e remanescentes, bacia, ZEE; aprovação do IAT', 'Proposta contígua à mata ciliar (corredor de {rl_corr} ha)'],
                     ['Art. 61-A §4º + Lei PR 18.295 art. 17 §2º', 'Imóvel de 4 a 10 MF com área consolidada em APP: recompor 20 m em cursos até 10 m; nascentes raio 15 m (art. 18)', 'Cenário B: {cenB} ha a recompor em vez de {app_rec} ha'],
                     ['Art. 29 §4º (Lei 14.595/2023)', 'Direito à adesão ao PRA para imóveis acima de 4 MF inscritos no CAR até 31/12/2023', 'Conferir a data de inscrição do CAR: sem ela vale o cenário A'],
                     ['Art. 66', 'Déficit de RL existente em 22/07/2008: recompor, regenerar ou compensar; até 20 anos, 1/10 a cada 2 anos; compensação no mesmo bioma (IN IAT 53/2025)', 'Déficit de {rl_def_com} ha a regularizar por uma ou mais alternativas'],
                     ['Art. 4º III, §1º, §4º', 'Reservatório por barramento: faixa da licença; menor que 1 ha dispensa faixa (vedada nova supressão)', 'Reservatório 19083 oscila entre 0,76 e 1,79 ha conforme a fonte: dispensa ambígua'],
                     ['STF ADI 4903 / ADC 42 (2018)', 'Nascentes e olhos d\'água intermitentes também geram APP; leito regular constitucional; art. 61-A válido', 'Perenidade da nascente não altera a APP; áreas consolidadas válidas'],
                     ['Lei 11.428/2006 + CONAMA 2/1994', 'Mata Atlântica: supressão condicionada ao estágio sucessional (parâmetros de DAP, área basal, estratos)', 'Estágio não se determina por satélite: inventário de campo obrigatório'],
                     ['IN MMA 2/2014; Manual SICAR', 'Camadas do CAR: Área Consolidada, Remanescente de Vegetação Nativa, APP/Uso Restrito por feição, Reserva Legal Proposta; datum SIRGAS 2000', 'Nomenclatura adotada no mapa M07 e nos vetores entregues']],
              'es': [['Dispositivo', 'Regla', 'Efecto para la Fazenda Santo Antônio'],
                     ['Art. 12, II', 'RL del 20% del inmueble fuera de la Amazonia Legal', '0,20 x {imovel_ha} ha = <b>{rl_ex} ha</b> (servidumbres administrativas asumidas en 0 ha — IN MMA 2/2014 art. 23)'],
                     ['Art. 15', 'La APP computa en la RL si: (I) no implica nueva conversión; (II) está conservada o en recuperación; (III) el inmueble está en el CAR', 'APP vegetada de {app_veg} ha sumada al remanente: disponible {rl_disp_com} ha'],
                     ['Art. 14', 'Localización de la RL: corredores con APP y remanentes, cuenca, ZEE; aprobación del IAT', 'Propuesta contigua al bosque ribereño (corredor de {rl_corr} ha)'],
                     ['Art. 61-A §4º + Ley PR 18.295 art. 17 §2º', 'Inmueble de 4 a 10 MF con área consolidada en APP: recomponer 20 m en cursos hasta 10 m; nascentes radio 15 m (art. 18)', 'Escenario B: {cenB} ha a recomponer en vez de {app_rec} ha'],
                     ['Art. 29 §4º (Ley 14.595/2023)', 'Derecho a adhesión al PRA para inmuebles de más de 4 MF inscritos en el CAR hasta el 31/12/2023', 'Verificar la fecha de inscripción del CAR: sin ella rige el escenario A'],
                     ['Art. 66', 'Déficit de RL existente el 22/07/2008: recomponer, regenerar o compensar; hasta 20 años, 1/10 cada 2 años; compensación en el mismo bioma (IN IAT 53/2025)', 'Déficit de {rl_def_com} ha a regularizar por una o más alternativas'],
                     ['Art. 4º III, §1º, §4º', 'Reservorio por represamiento: faja de la licencia; menor que 1 ha dispensa faja (prohibida nueva supresión)', 'El reservorio 19083 oscila entre 0,76 y 1,79 ha según la fuente: dispensa ambigua'],
                     ['STF ADI 4903 / ADC 42 (2018)', 'Nascentes intermitentes también generan APP; "leito regular" constitucional; art. 61-A válido', 'La perennidad de la nascente no altera la APP; áreas consolidadas válidas'],
                     ['Ley 11.428/2006 + CONAMA 2/1994', 'Mata Atlántica: supresión condicionada al estadio sucesional (parámetros de DAP, área basal, estratos)', 'El estadio no se determina por satélite: inventario de campo obligatorio'],
                     ['IN MMA 2/2014; Manual SICAR', 'Capas del CAR: Área Consolidada, Remanescente de Vegetação Nativa, APP/Uso Restrito por elemento, Reserva Legal Proposta; datum SIRGAS 2000', 'Nomenclatura adoptada en el mapa M07 y en los vectores entregados']]},
    's1_aviso': {'pt': '<b>Aviso.</b> O CAR é declaratório (art. 29) e a validação cabe ao IAT-PR, que analisa contra suas próprias bases (IN IAT 05/2023; Decreto PR 11.711/2025). O art. 68 (supressão anterior a 1989 conforme a lei da época) poderia reduzir a exigência de RL, mas depende de prova documental que não foi avaliada aqui.',
                 'es': '<b>Aviso.</b> El CAR es declarativo (art. 29) y la validación corresponde al IAT-PR, que analiza contra sus propias bases (IN IAT 05/2023; Decreto PR 11.711/2025). El art. 68 (supresión anterior a 1989 conforme a la ley de la época) podría reducir la exigencia de RL, pero depende de prueba documental que no se evaluó aquí.'},

    # ----------------------------------------------------------- sec 2 método ----
    's2_h': {'pt': 'Dados e método', 'es': 'Datos y método'},
    's2_t1_h': {'pt': 'Fontes de dados', 'es': 'Fuentes de datos'},
    's2_t1': {'pt': [['Fonte', 'Uso no diagnóstico', 'Resolução / data'],
                     ['Sentinel-2C L2A (S2_SR_HARMONIZED)', 'fundo dos mapas, índices, classificação RF, água aberta', '10 m · {escena_data} · {escena_id}'],
                     ['Cloud Score+ (cs_cdf)', 'máscara de nuvens da cena e da série NDVI', '10 m · limiar 0,60 / 0,65'],
                     ['FBDS / IAT-PR', 'cursos até 10 m, nascentes, massas d\'água, APP hídrica e uso 2013', 'RapidEye 5 m · 2013 · 1:25.000'],
                     ['IAT rede ottocodificada 2020; ANA BHO 2017 (5k); IBGE BC250 2025', 'consistência da hidrografia e regime (BC250)', '1:50.000 a 1:250.000'],
                     ['Copernicus DEM GLO-30', 'rede de drenagem D8, HAND, candidatos a nascente', '30 m · 2024_1'],
                     ['MapBiomas Coleção 11', 'cobertura 1985 / 2008 / 2025; área consolidada; mudança', '30 m (reamostrado a 10 m)'],
                     ['Dynamic World (moda 12 meses); ESA WorldCover 2021', 'rótulos de consenso para o RF e comparação de cobertura', '10 m'],
                     ['JRC Global Surface Water v1.4', 'ocorrência de água nos reservatórios', '30 m · 1984–2021'],
                     ['Hansen Global Forest Change 2025', 'perda de cobertura arbórea 2001–2025', '30 m'],
                     ['IBGE (malha municipal, biomas); INCRA (módulo fiscal)', 'localização, bioma, MF', '2024 / 2005']],
              'es': [['Fuente', 'Uso en el diagnóstico', 'Resolución / fecha'],
                     ['Sentinel-2C L2A (S2_SR_HARMONIZED)', 'fondo de los mapas, índices, clasificación RF, agua abierta', '10 m · {escena_data} · {escena_id}'],
                     ['Cloud Score+ (cs_cdf)', 'máscara de nubes de la escena y de la serie NDVI', '10 m · umbral 0,60 / 0,65'],
                     ['FBDS / IAT-PR', 'cursos hasta 10 m, nascentes, masas de agua, APP hídrica y uso 2013', 'RapidEye 5 m · 2013 · 1:25.000'],
                     ['IAT red ottocodificada 2020; ANA BHO 2017 (5k); IBGE BC250 2025', 'consistencia de la hidrografía y régimen (BC250)', '1:50.000 a 1:250.000'],
                     ['Copernicus DEM GLO-30', 'red de drenaje D8, HAND, candidatos a nascente', '30 m · 2024_1'],
                     ['MapBiomas Colección 11', 'cobertura 1985 / 2008 / 2025; área consolidada; cambio', '30 m (remuestreado a 10 m)'],
                     ['Dynamic World (moda 12 meses); ESA WorldCover 2021', 'etiquetas de consenso para el RF y comparación de cobertura', '10 m'],
                     ['JRC Global Surface Water v1.4', 'ocurrencia de agua en los reservorios', '30 m · 1984–2021'],
                     ['Hansen Global Forest Change 2025', 'pérdida de cobertura arbórea 2001–2025', '30 m'],
                     ['IBGE (malla municipal, biomas); INCRA (módulo fiscal)', 'localización, bioma, MF', '2024 / 2005']]},
    's2_pipe_h': {'pt': 'Pipeline em seis passos', 'es': 'Pipeline en seis pasos'},
    's2_pipe': {'pt': [
        '<b>1. Cena.</b> Seleção automática da melhor cena Sentinel-2 dos últimos 120 dias (cobertura 100% e nuvens 0% sobre o imóvel): {escena_data}. Download de bandas 10/20 m, SCL e Cloud Score+, tudo em EPSG:31982 com grade alinhada.',
        '<b>2. Hidrografia.</b> Recorte das bases oficiais ao imóvel + 500 m; rede de drenagem por DEM (pysheds, D8, limiar de 20 ha calibrado contra a FBDS) e HAND; distância entre fontes por tramo; candidatos a nascente = cabeceiras DEM sem nascente FBDS a menos de 60 m.',
        '<b>3. Água aberta.</b> MNDWI maior que 0 e NDVI menor que 0,30 (Otsu descartado por distribuição unimodal), filtro de 3 pixels; cruzamento com massas FBDS 2013 e ocorrência JRC; corpos com reflectância azul alta marcados como possíveis falsos positivos.',
        '<b>4. Vegetação nativa.</b> Random Forest (300 árvores, classes balanceadas) sobre 19 variáveis (bandas, NDVI, NDWI, MNDWI, NDMI, AWEI, NDRE, textura GLCM, HAND); rótulos por consenso MapBiomas x Dynamic World x WorldCover; validação espacial GroupKFold em blocos de 500 m; pós-processo moda 3x3 e área mínima 0,05 ha; fragmentos maiores ou iguais a 0,5 ha.',
        '<b>5. Buffers legais.</b> 30 m do eixo FBDS (cursos até 10 m) e 50 m das nascentes, recortados ao imóvel; cenário B com 20 m / 15 m; área consolidada pela cobertura MapBiomas 2008; reservatórios com faixa de 30 m só como cenário de referência.',
        '<b>6. RL e mapa CAR.</b> Remanescente fora da APP + APP vegetada (art. 15); proposta por dilatação iterativa de 10 m a partir da mata ciliar priorizando áreas não cultivadas; polígonos sem sobreposição que somam 100% do imóvel com a nomenclatura do SICAR.'],
        'es': [
        '<b>1. Escena.</b> Selección automática de la mejor escena Sentinel-2 de los últimos 120 días (cobertura 100% y nubes 0% sobre el inmueble): {escena_data}. Descarga de bandas 10/20 m, SCL y Cloud Score+, todo en EPSG:31982 con grilla alineada.',
        '<b>2. Hidrografía.</b> Recorte de las bases oficiales al inmueble + 500 m; red de drenaje por DEM (pysheds, D8, umbral de 20 ha calibrado contra la FBDS) y HAND; distancia entre fuentes por tramo; candidatos a nascente = cabeceras DEM sin nascente FBDS a menos de 60 m.',
        '<b>3. Agua abierta.</b> MNDWI mayor que 0 y NDVI menor que 0,30 (Otsu descartado por distribución unimodal), filtro de 3 píxeles; cruce con masas FBDS 2013 y ocurrencia JRC; cuerpos con reflectancia azul alta marcados como posibles falsos positivos.',
        '<b>4. Vegetación nativa.</b> Random Forest (300 árboles, clases balanceadas) sobre 19 variables (bandas, NDVI, NDWI, MNDWI, NDMI, AWEI, NDRE, textura GLCM, HAND); etiquetas por consenso MapBiomas x Dynamic World x WorldCover; validación espacial GroupKFold en bloques de 500 m; posproceso moda 3x3 y área mínima 0,05 ha; fragmentos mayores o iguales a 0,5 ha.',
        '<b>5. Buffers legales.</b> 30 m del eje FBDS (cursos hasta 10 m) y 50 m de las nascentes, recortados al inmueble; escenario B con 20 m / 15 m; área consolidada por la cobertura MapBiomas 2008; reservorios con faja de 30 m solo como escenario de referencia.',
        '<b>6. RL y mapa CAR.</b> Remanente fuera de la APP + APP vegetada (art. 15); propuesta por dilatación iterativa de 10 m desde el bosque ribereño priorizando áreas no cultivadas; polígonos sin superposición que suman 100% del inmueble con la nomenclatura del SICAR.']},
    's2_rf_h': {'pt': 'Exatidão da classificação (validação espacial por blocos)', 'es': 'Exactitud de la clasificación (validación espacial por bloques)'},
    's2_rf': {'pt': [['Classe', 'Amostras', 'F1', 'Exatidão do produtor', 'Exatidão do usuário'],
                     ['Floresta nativa', '{n_flor}', '{f1_flor}', '{pa_flor}', '{ua_flor}'],
                     ['Água', '{n_agua}', '{f1_agua}', '{pa_agua}', '{ua_agua}'],
                     ['Área antropizada', '{n_antr}', '{f1_antr}', '{pa_antr}', '{ua_antr}'],
                     ['Silvicultura', '{n_silv}', '{f1_silv}', '{pa_silv}', '{ua_silv}'],
                     ['<b>Global</b>', '{n_tot}', 'OA {oa} · kappa {kappa}', '', '']],
              'es': [['Clase', 'Muestras', 'F1', 'Exactitud del productor', 'Exactitud del usuario'],
                     ['Floresta nativa', '{n_flor}', '{f1_flor}', '{pa_flor}', '{ua_flor}'],
                     ['Agua', '{n_agua}', '{f1_agua}', '{pa_agua}', '{ua_agua}'],
                     ['Área antropizada', '{n_antr}', '{f1_antr}', '{pa_antr}', '{ua_antr}'],
                     ['Silvicultura', '{n_silv}', '{f1_silv}', '{pa_silv}', '{ua_silv}'],
                     ['<b>Global</b>', '{n_tot}', 'OA {oa} · kappa {kappa}', '', '']]},
    's2_rf_nota': {'pt': 'Os rótulos de treinamento vêm do consenso de três produtos globais, não de verdade de campo: a exatidão mede o acordo com esse consenso. A classe silvicultura (F1 {f1_silv}, {n_silv} amostras) é incerta e seus polígonos devem ser confirmados em campo. Uma classe de vegetação herbácea nativa não pôde ser treinada (menos de 200 pixels de consenso).',
                   'es': 'Las etiquetas de entrenamiento provienen del consenso de tres productos globales, no de verdad de campo: la exactitud mide el acuerdo con ese consenso. La clase silvicultura (F1 {f1_silv}, {n_silv} muestras) es incierta y sus polígonos deben confirmarse en campo. No pudo entrenarse una clase de vegetación herbácea nativa (menos de 200 píxeles de consenso).'},
    's2_ndvi_h': {'pt': 'Validação temporal: a faixa ciliar norte é vegetação permanente', 'es': 'Validación temporal: la faja ribereña norte es vegetación permanente'},
    's2_ndvi': {'pt': 'Para descartar que o fragmento 13 fosse cultivo, calculou-se a mediana mensal de NDVI por 24 meses (set/2024 a ago/2026) para o fragmento 13, a mata antiga (fragmento 2, floresta desde 1985) e os dois blocos de lavoura. O fragmento 13 fica entre {f13_min} e {f13_max} o ano inteiro, com a mesma sazonalidade da mata antiga ({f2_min}–{f2_max}); as lavouras caem a 0,11–0,19 na entressafra. Conclusão: vegetação permanente de porte arbóreo, não cultivo anual — compatível com regeneração natural em curso, cujo estágio só o campo determina.',
                'es': 'Para descartar que el fragmento 13 fuese cultivo, se calculó la mediana mensual de NDVI durante 24 meses (sep/2024 a ago/2026) para el fragmento 13, el monte antiguo (fragmento 2, floresta desde 1985) y los dos bloques de cultivo. El fragmento 13 se mantiene entre {f13_min} y {f13_max} todo el año, con la misma estacionalidad que el monte antiguo ({f2_min}–{f2_max}); los cultivos caen a 0,11–0,19 en la entre-zafra. Conclusión: vegetación permanente de porte arbóreo, no cultivo anual — compatible con regeneración natural en curso, cuyo estadio solo el campo determina.'},
    'g01_cap': {'pt': 'Figura G01 — NDVI mensal (mediana) de 24 meses: fragmento 13 vs mata antiga vs lavouras.', 'es': 'Figura G01 — NDVI mensual (mediana) de 24 meses: fragmento 13 vs monte antiguo vs cultivos.'},
    's2_inc_h': {'pt': 'Incerteza a declarar', 'es': 'Incertidumbre a declarar'},
    's2_inc': {'pt': [['Componente', 'Fonte', 'Incerteza planimétrica', 'Consequência sobre o buffer'],
                      ['Borda da vegetação arbórea', 'S2 10 m, classificação RF', '± 1 pixel = ± 10 m', 'Floresta no imóvel: {flor_rf} ha ± {flor_inc} ha (1 pixel de borda); numa faixa de 30 m, 10 m é um terço da largura'],
                      ['Borda da vegetação (referência)', 'MapBiomas 30 m', '± 30 m', 'Só contexto histórico; nunca para medir buffer'],
                      ['Eixo do curso d\'água', 'FBDS (RapidEye 5 m, 1:25.000)', '± 5–15 m (estimado pela escala; sem RMSE publicado)', 'APP de curso entre {app_curso_min} e {app_curso_max} ha conforme a posição do leito'],
                      ['Eixo do curso d\'água', 'DEM GLO-30', '± 30 m (DSM: dossel desloca o talvegue)', 'Só controle: rede DEM a {med_dem} m da FBDS (mediana), P90 {p90_dem} m'],
                      ['Nascente', 'FBDS ponto / cabeceira DEM', '± 15–30 m / ± 30–60 m', 'Raio de 50 m desloca-se até metade do seu tamanho: {app_nasc_min}–{app_nasc_max} ha'],
                      ['Largura do curso (até 10 m vs 10–50 m)', 'classe FBDS; S2 não mede', 'a medir em campo', 'Mudaria o buffer de 30 para 50 m']],
               'es': [['Componente', 'Fuente', 'Incertidumbre planimétrica', 'Consecuencia sobre el buffer'],
                      ['Borde de la vegetación arbórea', 'S2 10 m, clasificación RF', '± 1 píxel = ± 10 m', 'Floresta en el inmueble: {flor_rf} ha ± {flor_inc} ha (1 píxel de borde); en una faja de 30 m, 10 m es un tercio del ancho'],
                      ['Borde de la vegetación (referencia)', 'MapBiomas 30 m', '± 30 m', 'Solo contexto histórico; nunca para medir buffer'],
                      ['Eje del curso de agua', 'FBDS (RapidEye 5 m, 1:25.000)', '± 5–15 m (estimado por la escala; sin RMSE publicado)', 'APP de curso entre {app_curso_min} y {app_curso_max} ha según la posición del cauce'],
                      ['Eje del curso de agua', 'DEM GLO-30', '± 30 m (DSM: el dosel desplaza el talweg)', 'Solo control: red DEM a {med_dem} m de la FBDS (mediana), P90 {p90_dem} m'],
                      ['Nascente', 'FBDS punto / cabecera DEM', '± 15–30 m / ± 30–60 m', 'El radio de 50 m se desplaza hasta la mitad de su tamaño: {app_nasc_min}–{app_nasc_max} ha'],
                      ['Ancho del curso (hasta 10 m vs 10–50 m)', 'clase FBDS; S2 no lo mide', 'a medir en campo', 'Cambiaría el buffer de 30 a 50 m']]},
    'alcance_lbl': {'pt': 'Alcance', 'es': 'Alcance'},
    'alcance': {'pt': 'O presente diagnóstico satelital é <b>preliminar</b>; delimita cobertura vegetal com precisão de ±10 m e utiliza a hidrografia oficial FBDS/IAT (2013, 1:25.000) como referência do leito regular. Não constitui laudo com validade legal: o CAR é declaratório (Lei 12.651/2012, art. 29) e sua validação pelo IAT-PR segue a IN IAT 05/2023; a posição do leito regular e a perenidade das nascentes devem ser confirmadas em campo (GPS RTK) antes de qualquer uso administrativo.',
                'es': 'El presente diagnóstico satelital es <b>preliminar</b>; delimita cobertura vegetal con precisión de ±10 m y utiliza la hidrografía oficial FBDS/IAT (2013, 1:25.000) como referencia del "leito regular". No constituye un laudo con validez legal: el CAR es declarativo (Ley 12.651/2012, art. 29) y su validación por el IAT-PR sigue la IN IAT 05/2023; la posición del "leito regular" y la perennidad de las nascentes deben confirmarse en campo (GPS RTK) antes de cualquier uso administrativo.'},

    # ------------------------------------------------------------ sec 3 hidro ----
    's3_h': {'pt': 'Hidrografia', 'es': 'Hidrografía'},
    's3_intro': {'pt': 'A hidrografia legal do imóvel é a base FBDS/IAT-PR 2013: quatro tramos de curso d\'água "até 10 m" somando {km_fbds} km dentro do imóvel, uma nascente e três massas d\'água que o interceptam (duas dentro, artificiais, sobre o curso natural). As demais fontes servem de controle de posição e de regime.',
                 'es': 'La hidrografía legal del inmueble es la base FBDS/IAT-PR 2013: cuatro tramos de curso de agua "hasta 10 m" que suman {km_fbds} km dentro del inmueble, una nascente y tres masas de agua que lo interceptan (dos dentro, artificiales, sobre el curso natural). Las demás fuentes sirven de control de posición y de régimen.'},
    'm02_cap': {'pt': 'Mapa M02 — Hidrografia consolidada: FBDS (azul), rede DEM (cinza, controle), nascente FBDS, candidatos DEM e água aberta em 29/08/2026.',
                'es': 'Mapa M02 — Hidrografía consolidada: FBDS (azul), red DEM (gris, control), nascente FBDS, candidatos DEM y agua abierta el 29/08/2026.'},
    's3_t1_h': {'pt': 'Extensão dos cursos d\'água dentro do imóvel por fonte', 'es': 'Extensión de los cursos de agua dentro del inmueble por fuente'},
    's3_t1': {'pt': [['Fonte', 'km no imóvel', 'Tramos', 'Diferença vs FBDS', 'Papel'],
                     ['FBDS / IAT-PR 2013 (1:25.000)', '{km_fbds}', '4', '—', 'referência legal (leito)'],
                     ['IAT rede ottocodificada 2020', '{km_otto}', '4', '{dif_otto} km', 'confirma traçado'],
                     ['ANA BHO 2017 5k', '{km_ana}', '2', '{dif_ana} km', 'incompleta no imóvel'],
                     ['IBGE BC250 2025', '{km_ibge}', '2', '{dif_ibge} km', 'regime (perene)'],
                     ['Rede DEM GLO-30 (limiar 20 ha)', '{km_dem}', '6', '{dif_dem} km', 'controle; inclui cabeceiras não mapeadas']],
              'es': [['Fuente', 'km en inmueble', 'Tramos', 'Diferencia vs FBDS', 'Rol'],
                     ['FBDS / IAT-PR 2013 (1:25.000)', '{km_fbds}', '4', '—', 'referencia legal (cauce)'],
                     ['IAT red ottocodificada 2020', '{km_otto}', '4', '{dif_otto} km', 'confirma trazado'],
                     ['ANA BHO 2017 5k', '{km_ana}', '2', '{dif_ana} km', 'incompleta en el inmueble'],
                     ['IBGE BC250 2025', '{km_ibge}', '2', '{dif_ibge} km', 'régimen (perenne)'],
                     ['Red DEM GLO-30 (umbral 20 ha)', '{km_dem}', '6', '{dif_dem} km', 'control; incluye cabeceras no mapeadas']]},
    's3_consist': {'pt': '<b>Consistência FBDS vs DEM.</b> Dentro do imóvel, a rede derivada do relevo fica a {med_dem} m (mediana) e {p90_dem} m (P90) da linha FBDS; {pct30}% dos vértices a menos de 30 m. O DEM de 30 m é um modelo de superfície (inclui o dossel), por isso o talvegue sob mata ciliar se desloca: a rede DEM é controle, não referência. <b>Regime.</b> Só {km_perene} km coincidem (a menos de 30 m) com tramo "permanente" da BC250; os {km_nc} km restantes ficam "a classificar em campo" — a BC250 é 1:250.000 e a ausência de coincidência não significa curso intermitente. Os cursos intermitentes também geram APP; só os efêmeros não.',
                   'es': '<b>Consistencia FBDS vs DEM.</b> Dentro del inmueble, la red derivada del relieve queda a {med_dem} m (mediana) y {p90_dem} m (P90) de la línea FBDS; {pct30}% de los vértices a menos de 30 m. El DEM de 30 m es un modelo de superficie (incluye el dosel), por eso el talweg bajo bosque ribereño se desplaza: la red DEM es control, no referencia. <b>Régimen.</b> Solo {km_perene} km coinciden (a menos de 30 m) con un tramo "permanente" de la BC250; los {km_nc} km restantes quedan "a clasificar en campo" — la BC250 es 1:250.000 y la falta de coincidencia no significa curso intermitente. Los cursos intermitentes también generan APP; solo los efímeros no.'},
    's3_nasc_h': {'pt': 'Nascentes', 'es': 'Nascentes'},
    's3_nasc': {'pt': 'A base FBDS registra <b>1 nascente</b> dentro do imóvel (norte, cabeceira do curso que atravessa a faixa ciliar). A análise do relevo produziu <b>2 candidatos</b> (dem_1, a 97 m da nascente FBDS e 3 m do curso; dem_2, no talhão central, a 727 m de qualquer nascente FBDS). Não são nascentes até verificação em campo: se confirmados, somam {cand_app} ha de APP, dos quais {cand_add} ha fora da APP já exigível. A perenidade não é verificável por satélite; pela decisão do STF (ADI 4903) a nascente intermitente também gera APP.',
                'es': 'La base FBDS registra <b>1 nascente</b> dentro del inmueble (norte, cabecera del curso que atraviesa la faja ribereña). El análisis del relieve produjo <b>2 candidatos</b> (dem_1, a 97 m de la nascente FBDS y 3 m del curso; dem_2, en el lote central, a 727 m de cualquier nascente FBDS). No son nascentes hasta su verificación en campo: si se confirman, suman {cand_app} ha de APP, de las cuales {cand_add} ha fuera de la APP ya exigible. La perennidad no es verificable por satélite; por la decisión del STF (ADI 4903) la nascente intermitente también genera APP.'},
    's3_res_h': {'pt': 'Reservatórios artificiais por barramento', 'es': 'Reservorios artificiales por represamiento'},
    's3_res': {'pt': [['Reservatório (FBDS)', 'Espelho FBDS 2013', 'Espelho MNDWI 29/08/2026', 'Espelho RF água 2026', 'Ocorrência JRC', 'Dispensa art. 4º §4º (menor que 1 ha)', 'Faixa de 30 m (cenário)'],
                      ['19083 (Ribeirão do Salto)', '{r1_fbds} ha', '{r1_mndwi} ha', '{r1_rf} ha', '{r1_jrc}%', 'ambígua (as três medidas discordam no limiar de 1 ha)', '{r1_c30} ha ({r1_add} fora da APP exigível)'],
                      ['20452 (Ribeirão do Salto)', '{r2_fbds} ha', '{r2_mndwi} ha', '{r2_rf} ha', '{r2_jrc}%', 'sim pela FBDS', '{r2_c30} ha ({r2_add} fora da APP exigível)']],
               'es': [['Reservorio (FBDS)', 'Espejo FBDS 2013', 'Espejo MNDWI 29/08/2026', 'Espejo RF agua 2026', 'Ocurrencia JRC', 'Dispensa art. 4º §4º (menor que 1 ha)', 'Faja de 30 m (escenario)'],
                      ['19083 (Ribeirão do Salto)', '{r1_fbds} ha', '{r1_mndwi} ha', '{r1_rf} ha', '{r1_jrc}%', 'ambigua (las tres medidas discrepan en el umbral de 1 ha)', '{r1_c30} ha ({r1_add} fuera de la APP exigible)'],
                      ['20452 (Ribeirão do Salto)', '{r2_fbds} ha', '{r2_mndwi} ha', '{r2_rf} ha', '{r2_jrc}%', 'sí por la FBDS', '{r2_c30} ha ({r2_add} fuera de la APP exigible)']]},
    's3_res_nota': {'pt': 'Ambos represam o curso natural (art. 4º III): a faixa de APP é a definida na licença ambiental, desconhecida — registrada como "a definir pelo IAT" (IN IAT 64/2025) e <b>não somada</b> ao total exigível. O espelho medido na estação seca (MNDWI) subestima; o RF inclui margens úmidas e superestima; a FBDS 2013 é o nível de referência. Se o IAT fixar 30 m, a APP adicional seria de {res_add30} ha.',
                    'es': 'Ambos represan el curso natural (art. 4º III): la faja de APP es la definida en la licencia ambiental, desconocida — registrada como "a definir por el IAT" (IN IAT 64/2025) y <b>no sumada</b> al total exigible. El espejo medido en estación seca (MNDWI) subestima; el RF incluye márgenes húmedas y sobreestima; la FBDS 2013 es el nivel de referencia. Si el IAT fija 30 m, la APP adicional sería de {res_add30} ha.'},

    # -------------------------------------------------------- sec 4 vegetação ----
    's4_h': {'pt': 'Vegetação nativa', 'es': 'Vegetación nativa'},
    'm03_cap': {'pt': 'Mapa M03 — Classes Random Forest a 10 m e fragmentos de floresta com área dentro do imóvel; inset com a série NDVI de 24 meses.',
                'es': 'Mapa M03 — Clases Random Forest a 10 m y fragmentos de floresta con área dentro del inmueble; inset con la serie NDVI de 24 meses.'},
    's4_t1_h': {'pt': 'Cobertura dentro do imóvel segundo cada fonte (ha)', 'es': 'Cobertura dentro del inmueble según cada fuente (ha)'},
    's4_t1': {'pt': [['Fonte', 'Floresta / árvores', 'Água', 'Uso antrópico', 'Outros'],
                     ['RF 10 m (este diagnóstico)', '{rf_flor}', '{rf_agua}', '{rf_antr}', 'silvicultura {rf_silv}'],
                     ['MapBiomas 2025 (10 m)', '{mb_ff}', '{mb_rio}', 'soja {mb_soja}', 'mosaico de usos {mb_mos}'],
                     ['Dynamic World (moda 12 m)', '{dw_trees}', '{dw_water}', 'crops {dw_crops}', 'grass {dw_grass} · built {dw_built}'],
                     ['ESA WorldCover 2021', '{wc_tree}', '{wc_water}', 'cropland {wc_crop}', 'grassland {wc_grass} · built {wc_built}'],
                     ['FBDS uso 2013', '{fbds_ff}', '{fbds_agua}', '{fbds_antr}', '—']],
              'es': [['Fuente', 'Floresta / árboles', 'Agua', 'Uso antrópico', 'Otros'],
                     ['RF 10 m (este diagnóstico)', '{rf_flor}', '{rf_agua}', '{rf_antr}', 'silvicultura {rf_silv}'],
                     ['MapBiomas 2025 (10 m)', '{mb_ff}', '{mb_rio}', 'soja {mb_soja}', 'mosaico de usos {mb_mos}'],
                     ['Dynamic World (moda 12 m)', '{dw_trees}', '{dw_water}', 'crops {dw_crops}', 'grass {dw_grass} · built {dw_built}'],
                     ['ESA WorldCover 2021', '{wc_tree}', '{wc_water}', 'cropland {wc_crop}', 'grassland {wc_grass} · built {wc_built}'],
                     ['FBDS uso 2013', '{fbds_ff}', '{fbds_agua}', '{fbds_antr}', '—']]},
    's4_t1_nota': {'pt': 'A floresta RF no imóvel é de {flor_rf} ha (vetor), com faixa de {flor_min} a {flor_max} ha por ±1 pixel de borda. As fontes de 10 m (RF, Dynamic World, WorldCover) concordam em 16,6–20,4 ha; o MapBiomas (30 m) e a FBDS 2013 registram 5–7 ha porque não resolvem a faixa ciliar jovem.',
                   'es': 'La floresta RF en el inmueble es de {flor_rf} ha (vector), con banda de {flor_min} a {flor_max} ha por ±1 píxel de borde. Las fuentes de 10 m (RF, Dynamic World, WorldCover) coinciden en 16,6–20,4 ha; MapBiomas (30 m) y FBDS 2013 registran 5–7 ha porque no resuelven la faja ribereña joven.'},
    's4_t2_h': {'pt': 'Fragmentos de floresta (área mínima 0,5 ha)', 'es': 'Fragmentos de floresta (área mínima 0,5 ha)'},
    's4_t2': {'pt': [['Frag.', 'Área total', 'No imóvel', 'NDVI', 'NDRE', 'Prob. floresta', 'Floresta MB 1985 / 2008', 'HAND', 'Persistência (indicativo)']],
              'es': [['Frag.', 'Área total', 'En inmueble', 'NDVI', 'NDRE', 'Prob. floresta', 'Floresta MB 1985 / 2008', 'HAND', 'Persistencia (indicativo)']]},
    'persist': {'pt': {2: 'floresta desde 1985 (40 anos ou mais): vegetação mais antiga', 13: 'sem floresta em 2008: regeneração recente', 30: 'sem floresta em 2008: regeneração recente'},
                'es': {2: 'floresta desde 1985 (40 años o más): vegetación más antigua', 13: 'sin floresta en 2008: regeneración reciente', 30: 'sin floresta en 2008: regeneración reciente'}},
    's4_frag13': {'pt': '<b>Fragmento 13 — faixa ciliar norte ({f13_ha} ha, todo dentro do imóvel).</b> Sem histórico florestal em MapBiomas 2008 (0%), em 1985 (7%) nem na FBDS 2013; cobertura arbórea Hansen 2000 baixa. A série NDVI de 24 meses (§2) mostra vegetação permanente com sazonalidade de mata, não de lavoura. Textura GLCM mais homogênea que a mata antiga (contraste {f13_con} vs {f2_con}) e probabilidade de floresta {f13_prob}: indícios de dossel jovem e uniforme. Interpretação: <b>regeneração natural em curso</b> na faixa ciliar; a natureza (nativa vs plantio) e o estágio sucessional (CONAMA 2/1994) só se determinam em campo. Enquanto isso, a variante conservadora da RL exclui este fragmento.',
                  'es': '<b>Fragmento 13 — faja ribereña norte ({f13_ha} ha, todo dentro del inmueble).</b> Sin historial forestal en MapBiomas 2008 (0%), en 1985 (7%) ni en la FBDS 2013; cobertura arbórea Hansen 2000 baja. La serie NDVI de 24 meses (§2) muestra vegetación permanente con estacionalidad de monte, no de cultivo. Textura GLCM más homogénea que el monte antiguo (contraste {f13_con} vs {f2_con}) y probabilidad de floresta {f13_prob}: indicios de dosel joven y uniforme. Interpretación: <b>regeneración natural en curso</b> en la faja ribereña; la naturaleza (nativa vs plantación) y el estadio sucesional (CONAMA 2/1994) solo se determinan en campo. Mientras tanto, la variante conservadora de la RL excluye este fragmento.'},
    'm04_cap': {'pt': 'Mapa M04 — Mudança da cobertura florestal 2008 a 2025 (MapBiomas col. 11, 30 m) e perda Hansen por ano dentro do imóvel.',
                'es': 'Mapa M04 — Cambio de cobertura forestal 2008 a 2025 (MapBiomas col. 11, 30 m) y pérdida Hansen por año dentro del inmueble.'},
    's4_mud': {'pt': '<b>Mudança 2008 a 2025 (MapBiomas).</b> Floresta estável {mud_persist} ha; regeneração pós-2008 {mud_regen} ha; supressão pós-2008 {mud_supr} ha (indício de borda: pixels de 30 m na interface mata-lavoura); água {mud_agua} ha; antrópico estável {mud_antr} ha. O Hansen registra {hansen_tot} ha de perda no imóvel, toda em 2006 — <b>zero perda após 2008</b>, portanto a supressão do MapBiomas não é confirmada por uma segunda fonte. Dentro da APP, a parcela com floresta em 2008 e sem vegetação em 2026 é de apenas {supr08} ha.',
               'es': '<b>Cambio 2008 a 2025 (MapBiomas).</b> Floresta estable {mud_persist} ha; regeneración pos-2008 {mud_regen} ha; supresión pos-2008 {mud_supr} ha (indicio de borde: píxeles de 30 m en la interfaz monte-cultivo); agua {mud_agua} ha; antrópico estable {mud_antr} ha. Hansen registra {hansen_tot} ha de pérdida en el inmueble, toda en 2006 — <b>cero pérdida después de 2008</b>, por lo tanto la supresión de MapBiomas no está confirmada por una segunda fuente. Dentro de la APP, la porción con floresta en 2008 y sin vegetación en 2026 es de apenas {supr08} ha.'},

    # -------------------------------------------------------------- sec 5 APP ----
    's5_h': {'pt': 'Área de Preservação Permanente', 'es': 'Área de Preservação Permanente (APP)'},
    's5_intro': {'pt': 'A APP exigível é a soma do buffer de 30 m em torno do eixo FBDS dos cursos até 10 m ({app_curso} ha) e do raio de 50 m da nascente FBDS ({app_nasc} ha), recortada ao imóvel: <b>{app_ha} ha</b>, com faixa de {app_min} a {app_max} ha conforme a posição do leito (20 a 43 m do eixo). A cobertura de cada pedaço vem da classificação RF de 29/08/2026.',
                 'es': 'La APP exigible es la suma del buffer de 30 m alrededor del eje FBDS de los cursos hasta 10 m ({app_curso} ha) y del radio de 50 m de la nascente FBDS ({app_nasc} ha), recortada al inmueble: <b>{app_ha} ha</b>, con banda de {app_min} a {app_max} ha según la posición del cauce (20 a 43 m del eje). La cobertura de cada porción proviene de la clasificación RF del 29/08/2026.'},
    'm05_cap': {'pt': 'Mapa M05 — APP exigível por situação: conforme (verde), água (azul), a recompor (vermelho), silvicultura em APP (laranja); faixa do cenário B (magenta) e faixa "a definir" dos reservatórios (hachurado).',
                'es': 'Mapa M05 — APP exigible por situación: conforme (verde), agua (azul), a recomponer (rojo), silvicultura en APP (naranja); faja del escenario B (magenta) y faja "a definir" de los reservorios (rayado).'},
    'm05b_cap': {'pt': 'Mapa M05b — Detalhe norte: nascente FBDS, candidato dem_1 e faixa ciliar.', 'es': 'Mapa M05b — Detalle norte: nascente FBDS, candidato dem_1 y faja ribereña.'},
    'm05c_cap': {'pt': 'Mapa M05c — Detalhe sul: APP do Ribeirão do Salto e reservatórios 19083 / 20452.', 'es': 'Mapa M05c — Detalle sur: APP del Ribeirão do Salto y reservorios 19083 / 20452.'},
    's5_t1_h': {'pt': 'Balanço da APP exigível', 'es': 'Balance de la APP exigible'},
    's5_t1': {'pt': [['Componente', 'ha', 'Observação'],
                     ['APP de curso d\'água (30 m)', '{app_curso}', 'faixa {app_curso_min}–{app_curso_max} ha; desde a borda da calha estimada: {app_curso_borda} ha'],
                     ['APP de nascente (raio 50 m)', '{app_nasc}', 'faixa {app_nasc_min}–{app_nasc_max} ha; perenidade não verificada'],
                     ['<b>APP exigível total</b>', '<b>{app_ha}</b>', 'faixa {app_min}–{app_max} ha; controle DEM {dem_ctrl} ha (IoU {iou})'],
                     ['  com vegetação nativa (conforme)', '{app_veg}', '{pct_conf}% da APP; {pct_conf_agua}% se a água contar como conforme'],
                     ['  água (espelho dos reservatórios dentro da APP)', '{app_agua}', 'situação a definir com a faixa da licença'],
                     ['  sem vegetação nativa (a recompor)', '{app_rec}', 'dos quais silvicultura {app_silv} ha; área consolidada elegível {consol} ha; supressão pós-2008 {supr08} ha'],
                     ['Evolução 2013 a 2026', '{floresta2013} para {app_veg}', 'floresta dentro da mesma APP: FBDS uso 2013 vs RF 2026 (APP hídrica FBDS 2013 no imóvel: {app_fbds2013} ha)']],
              'es': [['Componente', 'ha', 'Observación'],
                     ['APP de curso de agua (30 m)', '{app_curso}', 'banda {app_curso_min}–{app_curso_max} ha; desde el borde del cauce estimado: {app_curso_borda} ha'],
                     ['APP de nascente (radio 50 m)', '{app_nasc}', 'banda {app_nasc_min}–{app_nasc_max} ha; perennidad no verificada'],
                     ['<b>APP exigible total</b>', '<b>{app_ha}</b>', 'banda {app_min}–{app_max} ha; control DEM {dem_ctrl} ha (IoU {iou})'],
                     ['  con vegetación nativa (conforme)', '{app_veg}', '{pct_conf}% de la APP; {pct_conf_agua}% si el agua cuenta como conforme'],
                     ['  agua (espejo de los reservorios dentro de la APP)', '{app_agua}', 'situación a definir con la faja de la licencia'],
                     ['  sin vegetación nativa (a recomponer)', '{app_rec}', 'de las cuales silvicultura {app_silv} ha; área consolidada elegible {consol} ha; supresión pos-2008 {supr08} ha'],
                     ['Evolución 2013 a 2026', '{floresta2013} a {app_veg}', 'floresta dentro de la misma APP: FBDS uso 2013 vs RF 2026 (APP hídrica FBDS 2013 en el inmueble: {app_fbds2013} ha)']]},
    's5_t2_h': {'pt': 'Cenários de recomposição', 'es': 'Escenarios de recomposición'},
    's5_t2': {'pt': [['Cenário', 'Base legal', 'A recompor', 'Condições'],
                     ['A — integral (30 m / 50 m)', 'art. 4º + art. 7º §1º', '<b>{cenA} ha</b> [{cenA_min}; {cenA_max}]', 'vale se o CAR não foi inscrito no prazo ou sem adesão ao PRA'],
                     ['B — PRA-PR (20 m / raio 15 m)', 'art. 61-A §4º + Lei PR 18.295 art. 17 §2º e 18', '<b>{cenB} ha</b> ({cenB_cons} consolidada na faixa + {supr08} supressão pós-2008); {cenB_borda} ha desde a borda da calha', 'CAR inscrito até 31/12/2023 + adesão ao PRA; excedente de {cenB_exc} ha continua APP com uso consolidado admitido'],
                     ['Adicionais não somados', 'art. 4º III e IV', 'reservatórios a 30 m: +{res_add30} ha · nascentes candidatas: +{cand_add} ha', 'dependem da licença do reservatório e da confirmação de campo']],
              'es': [['Escenario', 'Base legal', 'A recomponer', 'Condiciones'],
                     ['A — integral (30 m / 50 m)', 'art. 4º + art. 7º §1º', '<b>{cenA} ha</b> [{cenA_min}; {cenA_max}]', 'rige si el CAR no se inscribió en plazo o sin adhesión al PRA'],
                     ['B — PRA-PR (20 m / radio 15 m)', 'art. 61-A §4º + Ley PR 18.295 art. 17 §2º y 18', '<b>{cenB} ha</b> ({cenB_cons} consolidada en la faja + {supr08} supresión pos-2008); {cenB_borda} ha desde el borde del cauce', 'CAR inscrito hasta 31/12/2023 + adhesión al PRA; el excedente de {cenB_exc} ha sigue siendo APP con uso consolidado admitido'],
                     ['Adicionales no sumados', 'art. 4º III y IV', 'reservorios a 30 m: +{res_add30} ha · nascentes candidatas: +{cand_add} ha', 'dependen de la licencia del reservorio y de la confirmación de campo']]},
    's5_nota': {'pt': 'A área consolidada foi inferida da cobertura MapBiomas de 2008 (30 m reamostrado a 10 m): é indício, não prova; o IAT analisa com suas próprias bases (IN IAT 05/2023). O regime do art. 61-A não reduz a APP — apenas autoriza a continuidade do uso consolidado e fixa a faixa mínima a recompor.',
                'es': 'El área consolidada se infirió de la cobertura MapBiomas de 2008 (30 m remuestreado a 10 m): es indicio, no prueba; el IAT analiza con sus propias bases (IN IAT 05/2023). El régimen del art. 61-A no reduce la APP — solo autoriza la continuidad del uso consolidado y fija la faja mínima a recomponer.'},

    # --------------------------------------------------------------- sec 6 RL ----
    's6_h': {'pt': 'Reserva Legal', 'es': 'Reserva Legal'},
    'm06_cap': {'pt': 'Mapa M06 — Proposta de localização da Reserva Legal: remanescente fora da APP, APP computável (art. 15), APP a recompor incluída e corredor de recomposição.',
                'es': 'Mapa M06 — Propuesta de localización de la Reserva Legal: remanente fuera de la APP, APP computable (art. 15), APP a recomponer incluida y corredor de recomposición.'},
    's6_t1_h': {'pt': 'Balanço da Reserva Legal', 'es': 'Balance de la Reserva Legal'},
    's6_t1': {'pt': [['Item', 'ha', 'Observação'],
                     ['RL exigida (20% de {imovel_ha} ha)', '<b>{rl_ex}</b>', 'servidões administrativas: sem dado, assumidas 0 ha'],
                     ['Remanescente de vegetação nativa fora da APP', '{rl_rem}', 'floresta RF 2026; estágio a confirmar'],
                     ['Disponível sem computar a APP', '{rl_disp_sem}', 'déficit {rl_def_sem} ha'],
                     ['APP vegetada computável (art. 15)', '{app_veg}', 'exige CAR inscrito e APP conservada / em recuperação'],
                     ['<b>Disponível com APP (art. 15)</b>', '<b>{rl_disp_com}</b>', '<b>déficit {rl_def_com} ha</b> (incerteza da floresta ±{flor_inc} ha)'],
                     ['Variante conservadora (só floresta com histórico em 2008/2013)', '{rl_cons_rem} + {rl_cons_app}', 'déficit {rl_cons_def} ha se o fragmento 13 não for aceito como remanescente'],
                     ['Compensação mínima (art. 66 III) caso não se recomponha', '{rl_def_com}', 'mesmo bioma; IN IAT 53/2025']],
              'es': [['Ítem', 'ha', 'Observación'],
                     ['RL exigida (20% de {imovel_ha} ha)', '<b>{rl_ex}</b>', 'servidumbres administrativas: sin dato, asumidas 0 ha'],
                     ['Remanente de vegetación nativa fuera de la APP', '{rl_rem}', 'floresta RF 2026; estadio a confirmar'],
                     ['Disponible sin computar la APP', '{rl_disp_sem}', 'déficit {rl_def_sem} ha'],
                     ['APP vegetada computable (art. 15)', '{app_veg}', 'exige CAR inscrito y APP conservada / en recuperación'],
                     ['<b>Disponible con APP (art. 15)</b>', '<b>{rl_disp_com}</b>', '<b>déficit {rl_def_com} ha</b> (incertidumbre de la floresta ±{flor_inc} ha)'],
                     ['Variante conservadora (solo floresta con historial en 2008/2013)', '{rl_cons_rem} + {rl_cons_app}', 'déficit {rl_cons_def} ha si el fragmento 13 no se acepta como remanente'],
                     ['Compensación mínima (art. 66 III) si no se recompone', '{rl_def_com}', 'mismo bioma; IN IAT 53/2025']]},
    's6_prop': {'pt': '<b>Proposta de localização ({rl_prop} ha).</b> Composição: remanescente fora da APP {rl_rem} ha; APP incluída {rl_prop_app} ha (vegetada {rl_prop_app_veg} + a recompor {rl_prop_app_rec}; sem espelho d\'água); corredor de recomposição {rl_corr} ha, construído por dilatação iterativa de 10 m (7 iterações) a partir da mata ciliar, priorizando áreas não cultivadas e de menor NDVI (art. 14: contiguidade com APP e remanescentes). As parcelas se sobrepõem parcialmente nas bordas entre camadas, por isso a soma das partes difere do total em poucos décimos de hectare. A localização é uma <b>proposta sujeita à aprovação do IAT</b>; a APP só computa na RL se o CAR estiver inscrito e a APP conservada ou em recuperação.',
                'es': '<b>Propuesta de localización ({rl_prop} ha).</b> Composición: remanente fuera de la APP {rl_rem} ha; APP incluida {rl_prop_app} ha (vegetada {rl_prop_app_veg} + a recomponer {rl_prop_app_rec}; sin espejo de agua); corredor de recomposición {rl_corr} ha, construido por dilatación iterativa de 10 m (7 iteraciones) desde el bosque ribereño, priorizando áreas no cultivadas y de menor NDVI (art. 14: contigüidad con APP y remanentes). Las porciones se superponen parcialmente en los bordes entre capas, por eso la suma de las partes difiere del total en pocas décimas de hectárea. La localización es una <b>propuesta sujeta a aprobación del IAT</b>; la APP solo computa en la RL si el CAR está inscrito y la APP conservada o en recuperación.'},
    's6_alt_h': {'pt': 'Alternativas de regularização do déficit (art. 66)', 'es': 'Alternativas de regularización del déficit (art. 66)'},
    's6_alt': {'pt': [
        '<b>Regeneração natural</b> (art. 66 II) no corredor proposto: a faixa ciliar norte mostra que o processo já ocorre no imóvel; exige isolamento do gado/maquinário e controle de gramíneas.',
        '<b>Recomposição por plantio</b> (art. 66 I) de espécies nativas da Floresta Estacional Semidecidual, em até 20 anos, no mínimo 1/10 da área a cada 2 anos; sistema agroflorestal com até 50% de exóticas admitido (art. 66 §3º).',
        '<b>Compensação</b> (art. 66 III) de até {rl_def_com} ha no mesmo bioma — servidão ambiental, CRA, área equivalente ou doação em UC — preferencialmente na mesma formação fitogeográfica (IN IAT 53/2025).',
        'As três podem combinar-se. A escolha depende do custo de oportunidade da lavoura no corredor ({rl_corr} ha) e do resultado da verificação de campo do fragmento 13.'],
        'es': [
        '<b>Regeneración natural</b> (art. 66 II) en el corredor propuesto: la faja ribereña norte muestra que el proceso ya ocurre en el inmueble; exige aislamiento del ganado/maquinaria y control de gramíneas.',
        '<b>Recomposición por plantación</b> (art. 66 I) de especies nativas de la Floresta Estacional Semidecidual, en hasta 20 años, mínimo 1/10 del área cada 2 años; sistema agroforestal con hasta 50% de exóticas admitido (art. 66 §3º).',
        '<b>Compensación</b> (art. 66 III) de hasta {rl_def_com} ha en el mismo bioma — servidumbre ambiental, CRA, área equivalente o donación en UC — preferentemente en la misma formación fitogeográfica (IN IAT 53/2025).',
        'Las tres pueden combinarse. La elección depende del costo de oportunidad del cultivo en el corredor ({rl_corr} ha) y del resultado de la verificación de campo del fragmento 13.']},
    's6_serv': {'pt': '<b>Aviso sobre servidões.</b> A RL foi calculada sobre os {imovel_ha} ha totais. Se houver rodovia, linha de transmissão ou outra servidão administrativa dentro do perímetro, a base de cálculo diminui (IN MMA 2/2014 art. 23 I) — nenhuma foi identificada nas bases consultadas.',
                'es': '<b>Aviso sobre servidumbres.</b> La RL se calculó sobre las {imovel_ha} ha totales. Si hubiera carretera, línea de transmisión u otra servidumbre administrativa dentro del perímetro, la base de cálculo disminuye (IN MMA 2/2014 art. 23 I) — ninguna fue identificada en las bases consultadas.'},

    # -------------------------------------------------------------- sec 7 CAR ----
    's7_h': {'pt': 'Mapa de uso e cobertura com nomenclatura CAR', 'es': 'Mapa de uso y cobertura con nomenclatura CAR'},
    's7_intro': {'pt': 'O mapa M07 reorganiza o diagnóstico nas camadas que o Módulo de Cadastro do SICAR solicita (Cobertura do Solo, APP/Uso Restrito por feição, Reserva Legal Proposta), em polígonos sem sobreposição que fecham 100% do imóvel. Área de pousio: 0 ha (não identificável com uma única cena). Servidão administrativa: nenhuma identificada.',
                 'es': 'El mapa M07 reorganiza el diagnóstico en las capas que el Módulo de Cadastro del SICAR solicita (Cobertura do Solo, APP/Uso Restrito por elemento, Reserva Legal Proposta), en polígonos sin superposición que cierran el 100% del inmueble. Área de "pousio" (descanso): 0 ha (no identificable con una única escena). Servidumbre administrativa: ninguna identificada.'},
    'm07_cap': {'pt': 'Mapa M07 — Uso e cobertura com a nomenclatura CAR/SICAR e contorno da Reserva Legal Proposta.', 'es': 'Mapa M07 — Uso y cobertura con la nomenclatura CAR/SICAR y contorno de la Reserva Legal Propuesta.'},
    's7_t1': {'pt': [['Classe CAR', 'Subclasse', 'Situação', 'ha', 'Nota']], 'es': [['Clase CAR', 'Subclase', 'Situación', 'ha', 'Nota']]},
    'soma': {'pt': 'Soma (imóvel)', 'es': 'Suma (inmueble)'},
    'car_nota': {'pt': {'perenidade NAO verificada': 'perenidade não verificada', 'buffer 30 m do eixo FBDS 2013': 'buffer de 30 m do eixo FBDS 2013',
                        'faixa de APP a definir pelo IAT; espelho FBDS 2013 = 1.95 ha': 'faixa de APP a definir pelo IAT; espelho FBDS 2013 = 1,95 ha',
                        'estagio sucessional requer campo': 'estágio sucessional requer campo', 'uso antropico fora da APP': 'uso antrópico fora da APP',
                        'plantio florestal (RF); confirmar em campo': 'plantio florestal (RF); confirmar em campo'},
                 'es': {'perenidade NAO verificada': 'perennidad no verificada', 'buffer 30 m do eixo FBDS 2013': 'buffer de 30 m del eje FBDS 2013',
                        'faixa de APP a definir pelo IAT; espelho FBDS 2013 = 1.95 ha': 'faja de APP a definir por el IAT; espejo FBDS 2013 = 1,95 ha',
                        'estagio sucessional requer campo': 'estadio sucesional requiere campo', 'uso antropico fora da APP': 'uso antrópico fuera de la APP',
                        'plantio florestal (RF); confirmar em campo': 'plantación forestal (RF); confirmar en campo'}},
    'car_sit': {'pt': {'vegetacao nativa (RF 2026)': 'vegetação nativa (RF 2026)', 'sem vegetacao nativa': 'sem vegetação nativa', 'agua (RF 2026)': 'água (RF 2026)', 'conservada': 'conservada', 'consolidada': 'consolidada'},
                'es': {'vegetacao nativa (RF 2026)': 'vegetación nativa (RF 2026)', 'sem vegetacao nativa': 'sin vegetación nativa', 'agua (RF 2026)': 'agua (RF 2026)', 'conservada': 'conservada', 'consolidada': 'consolidada'}},
    'car_sub': {'pt': {'conforme': 'conforme', 'a recompor': 'a recompor', 'espelho d agua': 'espelho d\'água', 'floresta fora da APP': 'floresta fora da APP', 'uso agricola': 'uso agrícola', 'silvicultura': 'silvicultura'},
                'es': {'conforme': 'conforme', 'a recompor': 'a recomponer', 'espelho d agua': 'espejo de agua', 'floresta fora da APP': 'floresta fuera de la APP', 'uso agricola': 'uso agrícola', 'silvicultura': 'silvicultura'}},

    # ---------------------------------------------------- sec 8 limitações ----
    's8_h': {'pt': 'Limitações e próximos passos', 'es': 'Limitaciones y próximos pasos'},
    's8_lim_h': {'pt': 'O que este diagnóstico não afirma', 'es': 'Lo que este diagnóstico no afirma'},
    's8_lim': {'pt': [
        'O leito foi medido desde o <b>eixo</b> da linha FBDS 2013 (RapidEye 5 m, 1:25.000); a borda da calha do leito regular exige levantamento em campo (RTK). A faixa de {app_min} a {app_max} ha da APP traduz essa incerteza.',
        'A <b>perenidade</b> dos cursos e das nascentes não é verificável por satélite; o regime "perene" só foi atribuído onde coincide com a IBGE BC250 (1:250.000).',
        'A faixa de APP dos <b>reservatórios artificiais</b> é a da licença ambiental (art. 4º III; IN IAT 64/2025), desconhecida: não foi somada. O reservatório 19083 mede 1,44 ha na FBDS 2013, 0,76 ha no MNDWI 2026 (seca) e 1,79 ha no RF 2026 — a dispensa do §4º (menor que 1 ha) é ambígua.',
        'O <b>estágio sucessional</b> não se determina por satélite (CONAMA 2/1994 exige DAP, área basal, estratos): inventário de campo obrigatório para os três fragmentos.',
        'O cenário B (recomposição reduzida) exige <b>CAR inscrito até 31/12/2023 e adesão ao PRA</b>; sem essa condição vale o cenário A.',
        'A <b>área consolidada</b> foi inferida do MapBiomas 2008 (30 m): indício, não prova; o IAT analisa com suas próprias bases (IN IAT 05/2023).',
        'O <b>fragmento 13</b> não tem histórico florestal em 2000/2008/2013: vegetação arbórea jovem cuja natureza (regeneração nativa vs plantio) deve ser confirmada em campo; a variante conservadora da RL exclui-o.',
        'Os dois <b>candidatos DEM a nascente</b> são candidatos: se confirmados, somam {cand_add} ha de APP.',
        '<b>Servidões administrativas</b>: sem dado (assumidas 0 ha); RL = 20% x {imovel_ha} ha.',
        'A classificação RF foi treinada com consenso de três produtos globais (não verdade de campo); OA {oa} por blocos espaciais; silvicultura F1 {f1_silv}.',
        'Este diagnóstico é <b>preliminar</b> e não substitui laudo: o CAR é declaratório (art. 29) e a validação é do IAT-PR.'],
        'es': [
        'El cauce se midió desde el <b>eje</b> de la línea FBDS 2013 (RapidEye 5 m, 1:25.000); el borde del "leito regular" exige levantamiento en campo (RTK). La banda de {app_min} a {app_max} ha de la APP traduce esa incertidumbre.',
        'La <b>perennidad</b> de los cursos y de las nascentes no es verificable por satélite; el régimen "perenne" solo se atribuyó donde coincide con la IBGE BC250 (1:250.000).',
        'La faja de APP de los <b>reservorios artificiales</b> es la de la licencia ambiental (art. 4º III; IN IAT 64/2025), desconocida: no fue sumada. El reservorio 19083 mide 1,44 ha en la FBDS 2013, 0,76 ha en el MNDWI 2026 (seca) y 1,79 ha en el RF 2026 — la dispensa del §4º (menor que 1 ha) es ambigua.',
        'El <b>estadio sucesional</b> no se determina por satélite (CONAMA 2/1994 exige DAP, área basal, estratos): inventario de campo obligatorio para los tres fragmentos.',
        'El escenario B (recomposición reducida) exige <b>CAR inscrito hasta el 31/12/2023 y adhesión al PRA</b>; sin esa condición rige el escenario A.',
        'El <b>área consolidada</b> se infirió de MapBiomas 2008 (30 m): indicio, no prueba; el IAT analiza con sus propias bases (IN IAT 05/2023).',
        'El <b>fragmento 13</b> no tiene historial forestal en 2000/2008/2013: vegetación arbórea joven cuya naturaleza (regeneración nativa vs plantación) debe confirmarse en campo; la variante conservadora de la RL lo excluye.',
        'Los dos <b>candidatos DEM a nascente</b> son candidatos: si se confirman, suman {cand_add} ha de APP.',
        '<b>Servidumbres administrativas</b>: sin dato (asumidas 0 ha); RL = 20% x {imovel_ha} ha.',
        'La clasificación RF fue entrenada con consenso de tres productos globales (no verdad de campo); OA {oa} por bloques espaciales; silvicultura F1 {f1_silv}.',
        'Este diagnóstico es <b>preliminar</b> y no sustituye un laudo: el CAR es declarativo (art. 29) y la validación es del IAT-PR.']},
    's8_plan_h': {'pt': 'Plano de verificação recomendado', 'es': 'Plan de verificación recomendado'},
    's8_plan': {'pt': [['Passo', 'Ação', 'Resultado esperado'],
                       ['1', 'Levantamento GPS RTK da borda do leito regular ({km_fbds} km) e das nascentes (1 FBDS + 2 candidatos) na estação seca; pontos a cada 20–30 m e em cada quebra', 'APP definitiva (fecha a faixa {app_min}–{app_max} ha); nascentes confirmadas ou descartadas; largura dos cursos'],
                       ['2', 'Voo de drone (ortomosaico menor que 5 cm) sobre a mata ciliar e os reservatórios', 'borda arbórea a ±0,5 m; uso dentro da APP; espelho d\'água real dos reservatórios'],
                       ['3', 'Inventário florestal CONAMA 2/1994 nos fragmentos 2, 13 e 30 (DAP, área basal, estratos, espécies indicadoras)', 'estágio sucessional; natureza do fragmento 13 (regeneração nativa vs plantio)'],
                       ['4', 'Conferir data de inscrição e situação do CAR no SICAR-PR; licença dos reservatórios', 'define cenário A ou B; faixa de APP dos reservatórios'],
                       ['5', 'Protocolar / retificar o CAR com os vetores entregues e aderir ao PRA no IAT', 'Termo de Compromisso com prazos (APP 1/10 ao ano; RL 1/10 a cada 2 anos)'],
                       ['6', 'Plano de recomposição da APP ({cenA} ou {cenB} ha) e da RL (déficit {rl_def_com} ha): regeneração, plantio ou compensação', 'PRADA aprovado; cronograma e custo']],
                'es': [['Paso', 'Acción', 'Resultado esperado'],
                       ['1', 'Levantamiento GPS RTK del borde del "leito regular" ({km_fbds} km) y de las nascentes (1 FBDS + 2 candidatos) en estación seca; puntos cada 20–30 m y en cada quiebre', 'APP definitiva (cierra la banda {app_min}–{app_max} ha); nascentes confirmadas o descartadas; ancho de los cursos'],
                       ['2', 'Vuelo de dron (ortomosaico menor que 5 cm) sobre el bosque ribereño y los reservorios', 'borde arbóreo a ±0,5 m; uso dentro de la APP; espejo de agua real de los reservorios'],
                       ['3', 'Inventario forestal CONAMA 2/1994 en los fragmentos 2, 13 y 30 (DAP, área basal, estratos, especies indicadoras)', 'estadio sucesional; naturaleza del fragmento 13 (regeneración nativa vs plantación)'],
                       ['4', 'Verificar fecha de inscripción y situación del CAR en el SICAR-PR; licencia de los reservorios', 'define escenario A o B; faja de APP de los reservorios'],
                       ['5', 'Protocolar / rectificar el CAR con los vectores entregados y adherir al PRA en el IAT', 'Termo de Compromisso con plazos (APP 1/10 al año; RL 1/10 cada 2 años)'],
                       ['6', 'Plan de recomposición de la APP ({cenA} o {cenB} ha) y de la RL (déficit {rl_def_com} ha): regeneración, plantación o compensación', 'PRADA aprobado; cronograma y costo']]},

    # ------------------------------------------------------------- anexos ----
    'anexoA_h': {'pt': 'Anexo A — Fontes legais e científicas', 'es': 'Anexo A — Fuentes legales y científicas'},
    'anexoA_leg_h': {'pt': 'Fontes legais (consultadas em 06/09/2026)', 'es': 'Fuentes legales (consultadas el 06/09/2026)'},
    'anexoA_leg': {'pt': [['Norma', 'Conteúdo usado', 'URL'],
                          ['Lei 12.651/2012 (Código Florestal, compilado)', 'arts. 3º, 4º, 7º, 12, 14, 15, 29, 59, 61-A, 66', 'planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/L12651compilado.htm'],
                          ['Lei 11.428/2006 e Decreto 6.660/2008', 'Mata Atlântica: estágios e supressão', 'planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11428.htm'],
                          ['Lei 15.190/2025', 'revogação dos §§1º–2º do art. 14 da Lei 11.428', 'planalto.gov.br/ccivil_03/_ato2023-2026/2025/lei/L15190.htm'],
                          ['Decreto 7.830/2012', 'SICAR; rio perene / intermitente / efêmero', 'planalto.gov.br/ccivil_03/_ato2011-2014/2012/decreto/d7830.htm'],
                          ['IN MMA 2/2014', 'camadas do CAR, datum SIRGAS 2000, RL sem servidões', 'car.gov.br/leis/IN_CAR.pdf'],
                          ['Manual do Módulo de Cadastro CAR (SFB, via IAT)', 'nomenclatura das camadas', 'iat.pr.gov.br (manual_modulo_de_cadastro-car.pdf)'],
                          ['Resolução CONAMA 2/1994', 'estágios sucessionais no Paraná', 'snif.florestal.gov.br (resolucao_conama_02_1994.pdf)'],
                          ['Lei Estadual PR 18.295/2014', 'PRA-PR; art. 17 §2º–§3º, 18, 19', 'legislacao.pr.gov.br (codAto=132558)'],
                          ['Decreto Estadual PR 11.515/2018', 'regulamento do PRA-PR; prazos do Termo', 'legislacao.pr.gov.br (codAto=209637)'],
                          ['Decreto Estadual PR 11.711/2025', 'análise dinamizada do CAR-PR', 'legisweb.com.br/legislacao/?id=485957'],
                          ['IN IAT 53/2025', 'compensação de Reserva Legal', 'iat.pr.gov.br (instrucao_normativa_53-2025)'],
                          ['IN IAT 64/2025', 'APP de reservatórios artificiais', 'legisweb.com.br/legislacao/?id=486372'],
                          ['STF — julgamento 28/02/2018 (ADI 4901-4903, 4937; ADC 42)', 'nascentes intermitentes; leito regular; art. 61-A', 'portal.stf.jus.br (casos_notorios_2018); stf.jus.br (voto Fachin ADI4901.pdf)'],
                          ['INCRA/SNCR Índices Básicos 2005; Embrapa Módulo Fiscal', 'módulo fiscal de 20 ha', 'sistemafaep.org.br (Relacao-Alfabetica-por-SR.pdf); embrapa.br/codigo-florestal'],
                          ['IBGE Bioma Predominante por Município 2024', 'bioma Mata Atlântica', 'geoftp.ibge.gov.br (Bioma_Predominante_por_Municipio_2024.csv)']],
                   'es': [['Norma', 'Contenido usado', 'URL'],
                          ['Ley 12.651/2012 (Código Forestal, compilado)', 'arts. 3º, 4º, 7º, 12, 14, 15, 29, 59, 61-A, 66', 'planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/L12651compilado.htm'],
                          ['Ley 11.428/2006 y Decreto 6.660/2008', 'Mata Atlántica: estadios y supresión', 'planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11428.htm'],
                          ['Ley 15.190/2025', 'derogación de los §§1º–2º del art. 14 de la Ley 11.428', 'planalto.gov.br/ccivil_03/_ato2023-2026/2025/lei/L15190.htm'],
                          ['Decreto 7.830/2012', 'SICAR; río perenne / intermitente / efímero', 'planalto.gov.br/ccivil_03/_ato2011-2014/2012/decreto/d7830.htm'],
                          ['IN MMA 2/2014', 'capas del CAR, datum SIRGAS 2000, RL sin servidumbres', 'car.gov.br/leis/IN_CAR.pdf'],
                          ['Manual del Módulo de Cadastro CAR (SFB, vía IAT)', 'nomenclatura de las capas', 'iat.pr.gov.br (manual_modulo_de_cadastro-car.pdf)'],
                          ['Resolución CONAMA 2/1994', 'estadios sucesionales en Paraná', 'snif.florestal.gov.br (resolucao_conama_02_1994.pdf)'],
                          ['Ley Estadual PR 18.295/2014', 'PRA-PR; art. 17 §2º–§3º, 18, 19', 'legislacao.pr.gov.br (codAto=132558)'],
                          ['Decreto Estadual PR 11.515/2018', 'reglamento del PRA-PR; plazos del Termo', 'legislacao.pr.gov.br (codAto=209637)'],
                          ['Decreto Estadual PR 11.711/2025', 'análisis dinamizado del CAR-PR', 'legisweb.com.br/legislacao/?id=485957'],
                          ['IN IAT 53/2025', 'compensación de Reserva Legal', 'iat.pr.gov.br (instrucao_normativa_53-2025)'],
                          ['IN IAT 64/2025', 'APP de reservorios artificiales', 'legisweb.com.br/legislacao/?id=486372'],
                          ['STF — fallo 28/02/2018 (ADI 4901-4903, 4937; ADC 42)', 'nascentes intermitentes; leito regular; art. 61-A', 'portal.stf.jus.br (casos_notorios_2018); stf.jus.br (voto Fachin ADI4901.pdf)'],
                          ['INCRA/SNCR Índices Básicos 2005; Embrapa Módulo Fiscal', 'módulo fiscal de 20 ha', 'sistemafaep.org.br (Relacao-Alfabetica-por-SR.pdf); embrapa.br/codigo-florestal'],
                          ['IBGE Bioma Predominante por Município 2024', 'bioma Mata Atlántica', 'geoftp.ibge.gov.br (Bioma_Predominante_por_Municipio_2024.csv)']]},
    'anexoA_sci_h': {'pt': 'Fontes científicas (DOIs verificados na Crossref em 06/09/2026)', 'es': 'Fuentes científicas (DOIs verificados en Crossref el 06/09/2026)'},
    'anexoA_sci': {'pt': [
        'Xu, 2006, Int. J. Remote Sensing — MNDWI. DOI 10.1080/01431160600589179',
        'McFeeters, 1996, Int. J. Remote Sensing — NDWI. DOI 10.1080/01431169608948714',
        'Feyisa, Meilby, Fensholt, 2014, Remote Sens. Environ. — AWEI. DOI 10.1016/j.rse.2013.08.029',
        'Pekel, Cottam, Gorelick, Belward, 2016, Nature — Global Surface Water. DOI 10.1038/nature20584',
        'Rennó et al., 2008, Remote Sens. Environ. — HAND. DOI 10.1016/j.rse.2008.03.018',
        "O'Callaghan &amp; Mark, 1984, CVGIP — D8 e acumulação de fluxo. DOI 10.1016/S0734-189X(84)80011-0",
        'Guth &amp; Geoffroy, 2021, Transactions in GIS — precisão do Copernicus DEM. DOI 10.1111/tgis.12825',
        'Souza et al., 2020, Remote Sensing — método MapBiomas. DOI 10.3390/rs12172735',
        'Hansen et al., 2013, Science — Global Forest Change. DOI 10.1126/science.1244693',
        'Brown et al., 2022, Scientific Data — Dynamic World. DOI 10.1038/s41597-022-01307-4',
        'Zanaga et al., 2022, Zenodo — ESA WorldCover v200. DOI 10.5281/zenodo.7254221',
        'Breiman, 2001, Machine Learning — Random Forest. DOI 10.1023/A:1010933404324',
        'Belgiu &amp; Dragut, 2016, ISPRS J. Photogramm. — RF em sensoriamento remoto. DOI 10.1016/j.isprsjprs.2016.01.011',
        'Haralick, Shanmugam, Dinstein, 1973, IEEE TSMC — textura GLCM. DOI 10.1109/TSMC.1973.4309314',
        'Gorelick et al., 2017, Remote Sens. Environ. — Google Earth Engine. DOI 10.1016/j.rse.2017.06.031'],
        'es': [
        'Xu, 2006, Int. J. Remote Sensing — MNDWI. DOI 10.1080/01431160600589179',
        'McFeeters, 1996, Int. J. Remote Sensing — NDWI. DOI 10.1080/01431169608948714',
        'Feyisa, Meilby, Fensholt, 2014, Remote Sens. Environ. — AWEI. DOI 10.1016/j.rse.2013.08.029',
        'Pekel, Cottam, Gorelick, Belward, 2016, Nature — Global Surface Water. DOI 10.1038/nature20584',
        'Rennó et al., 2008, Remote Sens. Environ. — HAND. DOI 10.1016/j.rse.2008.03.018',
        "O'Callaghan &amp; Mark, 1984, CVGIP — D8 y acumulación de flujo. DOI 10.1016/S0734-189X(84)80011-0",
        'Guth &amp; Geoffroy, 2021, Transactions in GIS — precisión del Copernicus DEM. DOI 10.1111/tgis.12825',
        'Souza et al., 2020, Remote Sensing — método MapBiomas. DOI 10.3390/rs12172735',
        'Hansen et al., 2013, Science — Global Forest Change. DOI 10.1126/science.1244693',
        'Brown et al., 2022, Scientific Data — Dynamic World. DOI 10.1038/s41597-022-01307-4',
        'Zanaga et al., 2022, Zenodo — ESA WorldCover v200. DOI 10.5281/zenodo.7254221',
        'Breiman, 2001, Machine Learning — Random Forest. DOI 10.1023/A:1010933404324',
        'Belgiu &amp; Dragut, 2016, ISPRS J. Photogramm. — RF en teledetección. DOI 10.1016/j.isprsjprs.2016.01.011',
        'Haralick, Shanmugam, Dinstein, 1973, IEEE TSMC — textura GLCM. DOI 10.1109/TSMC.1973.4309314',
        'Gorelick et al., 2017, Remote Sens. Environ. — Google Earth Engine. DOI 10.1016/j.rse.2017.06.031']},
    'anexoB_h': {'pt': 'Anexo B — Inventário de arquivos entregues', 'es': 'Anexo B — Inventario de archivos entregados'},
    'anexoB_intro': {'pt': 'Todos os vetores de entrega estão em SIRGAS 2000 geográfico (EPSG:4674, datum do CAR) nos formatos GeoJSON, Shapefile e KML; os arquivos de análise ficam em EPSG:31982. O arquivo LEIAME.txt descreve cada campo.',
                     'es': 'Todos los vectores de entrega están en SIRGAS 2000 geográfico (EPSG:4674, datum del CAR) en formatos GeoJSON, Shapefile y KML; los archivos de análisis quedan en EPSG:31982. El archivo LEIAME.txt describe cada campo.'},
    'anexoB': {'pt': [['Pasta / arquivo', 'Conteúdo'],
                      ['04_VETORES_ENTREGA/mapa_uso_car.*', 'uso e cobertura com nomenclatura CAR (8 polígonos, 157,75 ha)'],
                      ['04_VETORES_ENTREGA/APP.*', 'APP exigível por feição e situação (conforme / a recompor)'],
                      ['04_VETORES_ENTREGA/RL_proposta.*', 'Reserva Legal Proposta (31,57 ha)'],
                      ['04_VETORES_ENTREGA/hidrografia_consolidada.*', 'cursos d\'água por fonte (FBDS, otto, ANA, IBGE, DEM) com regime e comprimento'],
                      ['04_VETORES_ENTREGA/nascentes_consolidadas.*', 'nascente FBDS e candidatos DEM (validar_campo)'],
                      ['04_VETORES_ENTREGA/vegetacao_nativa_10m.*', 'classes RF 2026 (floresta nativa, água, área antropizada, silvicultura)'],
                      ['04_VETORES_ENTREGA/massas_dagua_propriedade.*', 'reservatórios FBDS com espelho 2013 / 2026 e situação art. 4º'],
                      ['04_VETORES_ENTREGA/LEIAME.txt', 'descrição bilíngue dos campos e dos formatos'],
                      ['03_MAPAS/M01…M07, G01 (.png)', 'mapas temáticos em A4 vertical (250 dpi) e A4 apaisado (A4_horizontal/); versão em espanhol em ES/'],
                      ['02_ANALISIS/resultados_analisis.json', 'todas as cifras deste relatório (hidrografia, vegetação, legal)'],
                      ['02_ANALISIS/*.tif', 'vegetacao_10m_2026-08-29 (classes RF), prob_floresta_nativa_10m, HAND_30m, agua_s2_2026-08-29_10m'],
                      ['02_ANALISIS/*.geojson', 'fragmentos_floresta, mudanca_2008_2025, RL_corredor_recomposicao, agua_s2, hidro_dem_red (EPSG:31982 e WGS 84)'],
                      ['01_DATOS_SATELITE/', 'Sentinel-2 29/08/2026 (bandas, índices, RGB, SCL), DEM GLO-30, MapBiomas, Dynamic World, WorldCover, JRC, Hansen'],
                      ['Diagnostico_APP_RL_Fazenda_Santo_Antonio_PT.pdf / _ES.pdf', 'este relatório em português e em espanhol']],
               'es': [['Carpeta / archivo', 'Contenido'],
                      ['04_VETORES_ENTREGA/mapa_uso_car.*', 'uso y cobertura con nomenclatura CAR (8 polígonos, 157,75 ha)'],
                      ['04_VETORES_ENTREGA/APP.*', 'APP exigible por elemento y situación (conforme / a recomponer)'],
                      ['04_VETORES_ENTREGA/RL_proposta.*', 'Reserva Legal Propuesta (31,57 ha)'],
                      ['04_VETORES_ENTREGA/hidrografia_consolidada.*', 'cursos de agua por fuente (FBDS, otto, ANA, IBGE, DEM) con régimen y longitud'],
                      ['04_VETORES_ENTREGA/nascentes_consolidadas.*', 'nascente FBDS y candidatos DEM (validar_campo)'],
                      ['04_VETORES_ENTREGA/vegetacao_nativa_10m.*', 'clases RF 2026 (floresta nativa, agua, área antropizada, silvicultura)'],
                      ['04_VETORES_ENTREGA/massas_dagua_propriedade.*', 'reservorios FBDS con espejo 2013 / 2026 y situación art. 4º'],
                      ['04_VETORES_ENTREGA/LEIAME.txt', 'descripción bilingüe de los campos y de los formatos'],
                      ['03_MAPAS/M01…M07, G01 (.png)', 'mapas temáticos en A4 vertical (250 dpi) y A4 apaisado (A4_horizontal/); versión en español en ES/'],
                      ['02_ANALISIS/resultados_analisis.json', 'todas las cifras de este informe (hidrografía, vegetación, legal)'],
                      ['02_ANALISIS/*.tif', 'vegetacao_10m_2026-08-29 (clases RF), prob_floresta_nativa_10m, HAND_30m, agua_s2_2026-08-29_10m'],
                      ['02_ANALISIS/*.geojson', 'fragmentos_floresta, mudanca_2008_2025, RL_corredor_recomposicao, agua_s2, hidro_dem_red (EPSG:31982 y WGS 84)'],
                      ['01_DATOS_SATELITE/', 'Sentinel-2 29/08/2026 (bandas, índices, RGB, SCL), DEM GLO-30, MapBiomas, Dynamic World, WorldCover, JRC, Hansen'],
                      ['Diagnostico_APP_RL_Fazenda_Santo_Antonio_PT.pdf / _ES.pdf', 'este informe en portugués y en español']]},
    'm01_cap': {'pt': 'Mapa M01 — Localização do imóvel e área de análise sobre a cena Sentinel-2 de 29/08/2026; inset do município.',
                'es': 'Mapa M01 — Localización del inmueble y área de análisis sobre la escena Sentinel-2 del 29/08/2026; inset del municipio.'},
    'fig': {'pt': 'Figura', 'es': 'Figura'},
}
