# -*- coding: utf-8 -*-
"""textos_v2 — textos PT/ES do dictamen preliminar por gleba (an_09_informe_v2).

Placeholders {..} sao preenchidos pelo dict V de an_09 (cifras ja formatadas com virgula decimal).
Helvetica/WinAnsi: sem "menor ou igual", setas ou subindices Unicode.
"""

TXT = {
    'footer': {'pt': 'Santo Antônio · APP/RL por gleba · 09/2026', 'es': 'Santo Antônio · APP/RL por gleba · 09/2026'},
    'cover_title': {'pt': 'Mata Ciliar e Reserva Legal por Gleba', 'es': 'Mata Ciliar y Reserva Legal por Gleba'},
    'cover_sub': {'pt': 'Fazenda Santo Antônio · São Sebastião da Amoreira – PR · Dictame preliminar',
                  'es': 'Fazenda Santo Antônio · São Sebastião da Amoreira – PR · Dictamen preliminar'},
    'ficha_h': {'pt': 'Ficha do diagnóstico', 'es': 'Ficha del diagnóstico'},
    'ficha': {'pt': [
        ['Cliente', 'Sonia Maria Bigati'],
        ['Imóvel', 'Fazenda Santo Antônio – {tot_ha} ha em duas glebas avaliadas SEPARADAMENTE: Gleba 1 (imóvel principal) {g1_ha} ha · Gleba 2 ("os 6 alqueires", comprada à parte) {g2_ha} ha = {g2_alq} alqueires paulistas de 2,42 ha'],
        ['Município', 'São Sebastião da Amoreira – PR (IBGE 4126009), Norte Pioneiro'],
        ['Módulo fiscal', '{mf} ha (INCRA) · {n_mf} MF: média propriedade (mais de 4 e até 10 MF)'],
        ['Bioma', 'Mata Atlântica (IBGE 2024); Floresta Estacional Semidecidual provável, a confirmar'],
        ['Cena e CRS', 'Sentinel-2C L2A 29/08/2026 ({escena_id}), sem nuvens · SIRGAS 2000 / UTM 22S (EPSG:31982); entrega em EPSG:4674'],
        ['Alcance', 'SÓ o interior do perímetro: nenhum dado de vizinhos, do município ou de fora do limite entra nos números ou nos mapas'],
        ['Emissão e responsável', '06/09/2026 · Eng. Agr. Nilton Camargo, Director Técnico – Pixadvisor Agricultura de Precisão · nilton.camargo@pixadvisor.network · +591 721 49171']],
        'es': [
        ['Cliente', 'Sonia Maria Bigati'],
        ['Inmueble', 'Fazenda Santo Antônio – {tot_ha} ha en dos glebas evaluadas POR SEPARADO: Gleba 1 (inmueble principal) {g1_ha} ha · Gleba 2 ("los 6 alqueires", comprada aparte) {g2_ha} ha = {g2_alq} alqueires paulistas de 2,42 ha'],
        ['Municipio', 'São Sebastião da Amoreira – PR (IBGE 4126009), Norte Pioneiro'],
        ['Módulo fiscal', '{mf} ha (INCRA) · {n_mf} MF: propiedad media (más de 4 y hasta 10 MF)'],
        ['Bioma', 'Mata Atlántica (IBGE 2024); Floresta Estacional Semidecidual probable, a confirmar'],
        ['Escena y CRS', 'Sentinel-2C L2A 29/08/2026 ({escena_id}), sin nubes · SIRGAS 2000 / UTM 22S (EPSG:31982); entrega en EPSG:4674'],
        ['Alcance', 'SOLO el interior del perímetro: ningún dato de vecinos, del municipio o de fuera del límite entra en los números ni en los mapas'],
        ['Emisión y responsable', '06/09/2026 · Ing. Agr. Nilton Camargo, Director Técnico – Pixadvisor Agricultura de Precisión · nilton.camargo@pixadvisor.network · +591 721 49171']]},
    'linha_lbl': {'pt': 'Em uma linha', 'es': 'En una línea'},
    'linha': {'pt': 'Santo Antônio NÃO está integralmente dentro da norma: a Gleba 1 ({g1_ha} ha) tem mata ciliar incompleta ({g1_app_rec} ha de APP a recompor, '
                    'ou {g1_pra} ha pela faixa reduzida do PRA-PR) e Reserva Legal com déficit de {g1_rl_def} ha (existem {g1_rl_exist} dos {g1_rl_ex} ha exigidos). '
                    'A Gleba 2 ({g2_ha} ha, {g2_alq} alqueires) tem a APP conforme e precisa de {g2_rl_ex} ha de vegetação nativa para a Reserva Legal: '
                    'a imagem mostra {g2_hoje} ha na ponta norte (déficit de {g2_rl_def} ha), mas só valem se essa floresta pertencer à gleba, o que o cliente contesta e deve ser confirmado em campo e na escritura.',
              'es': 'Santo Antônio NO está íntegramente dentro de la norma: la Gleba 1 ({g1_ha} ha) tiene mata ciliar incompleta ({g1_app_rec} ha de APP a recomponer, '
                    'o {g1_pra} ha por la faja reducida del PRA-PR) y Reserva Legal con déficit de {g1_rl_def} ha (existen {g1_rl_exist} de las {g1_rl_ex} ha exigidas). '
                    'La Gleba 2 ({g2_ha} ha, {g2_alq} alqueires) tiene la APP conforme y necesita {g2_rl_ex} ha de vegetación nativa para la Reserva Legal: '
                    'la imagen muestra {g2_hoje} ha en la punta norte (déficit de {g2_rl_def} ha), pero solo valen si esa floresta pertenece a la gleba, lo que el cliente discute y debe confirmarse en campo y en la escritura.'},
    # 1. resposta direta
    's1_h': {'pt': 'Resposta direta: Santo Antônio está na norma?', 'es': 'Respuesta directa: ¿Santo Antônio está en la norma?'},
    's1_intro': {'pt': 'Cada gleba foi avaliada como um imóvel próprio, com sua APP e sua Reserva Legal de 20%. Nenhum hectare de uma gleba conta para a outra. '
                       'A tabela responde por item; os números que faltam são os que a imagem de 29/08/2026 e a hidrografia oficial FBDS/IAT sustentam.',
                 'es': 'Cada gleba fue evaluada como un inmueble propio, con su APP y su Reserva Legal del 20%. Ninguna hectárea de una gleba cuenta para la otra. '
                       'La tabla responde por ítem; los números que faltan son los que la imagen del 29/08/2026 y la hidrografía oficial FBDS/IAT sostienen.'},
    'kpi': {'pt': [('{g1_app_rec} ha', 'APP a recompor na Gleba 1 (cenário integral)'), ('{g1_rl_def} ha', 'déficit de Reserva Legal na Gleba 1'),
                   ('{g2_rl_ex} ha', 'vegetação nativa que a Gleba 2 precisa (RL 20%)'), ('{g2_hoje} ha', 'floresta que a imagem mostra na Gleba 2')],
            'es': [('{g1_app_rec} ha', 'APP a recomponer en la Gleba 1 (escenario integral)'), ('{g1_rl_def} ha', 'déficit de Reserva Legal en la Gleba 1'),
                   ('{g2_rl_ex} ha', 'vegetación nativa que la Gleba 2 necesita (RL 20%)'), ('{g2_hoje} ha', 'floresta que la imagen muestra en la Gleba 2')]},
    's1_t1_h': {'pt': 'Está na norma? Veredito por gleba e por item', 'es': '¿Está en la norma? Veredicto por gleba y por ítem'},
    's1_t1': {'pt': [['Gleba', 'Item', 'Veredito', 'O que falta'],
                     ['Gleba 1 ({g1_ha} ha)', 'Mata ciliar (APP)', '<b>NÃO CONFORME</b>', 'Recompor {g1_app_rec} ha (30 m / 50 m). Pelo PRA-PR (20 m / 15 m, exige CAR até 31/12/2023 e adesão): {g1_pra} ha. Se o IAT aplicar a faixa de 30 m do reservatório: {g1_appF_rec} ha'],
                     ['Gleba 1 ({g1_ha} ha)', 'Reserva Legal (20% = {g1_rl_ex} ha)', '<b>NÃO CONFORME</b>', 'Faltam {g1_rl_def} ha (existem {g1_rl_exist} ha: {g1_rem} ha de remanescente + {g1_app_veg} ha de APP vegetada, art. 15). Sem computar a APP faltariam {g1_rl_def_sem} ha'],
                     ['Gleba 2 ({g2_ha} ha)', 'Mata ciliar (APP)', '<b>CONFORME</b>', 'APP de {g2_app} ha ({a1_g2} m do Arroio 1 na ponta norte) totalmente com vegetação nativa. Sem nascente nem reservatório'],
                     ['Gleba 2 ({g2_ha} ha)', 'Reserva Legal (20% = {g2_rl_ex} ha)', '<b>NÃO CONFORME</b> (por {g2_rl_def} ha) – condicionado', 'Precisa de {g2_rl_ex} ha de vegetação nativa. A imagem mostra {g2_hoje} ha na ponta norte: faltam {g2_rl_def} ha. Se essa floresta não pertencer à gleba (versão do cliente), faltam os {g2_rl_ex} ha inteiros'],
                     ['Imóvel único ({tot_ha} ha)', 'APP + RL (variante, CAR em uma matrícula)', '<b>NÃO CONFORME</b>', 'APP a recompor {un_app_rec} ha (PRA-PR {un_pra} ha); RL {un_rl_ex} ha, existente {un_rl_exist} ha, déficit {un_rl_def} ha']],
              'es': [['Gleba', 'Ítem', 'Veredicto', 'Qué falta'],
                     ['Gleba 1 ({g1_ha} ha)', 'Mata ciliar (APP)', '<b>NO CONFORME</b>', 'Recomponer {g1_app_rec} ha (30 m / 50 m). Por el PRA-PR (20 m / 15 m, exige CAR hasta el 31/12/2023 y adhesión): {g1_pra} ha. Si el IAT aplica la faja de 30 m del reservorio: {g1_appF_rec} ha'],
                     ['Gleba 1 ({g1_ha} ha)', 'Reserva Legal (20% = {g1_rl_ex} ha)', '<b>NO CONFORME</b>', 'Faltan {g1_rl_def} ha (existen {g1_rl_exist} ha: {g1_rem} ha de remanente + {g1_app_veg} ha de APP vegetada, art. 15). Sin computar la APP faltarían {g1_rl_def_sem} ha'],
                     ['Gleba 2 ({g2_ha} ha)', 'Mata ciliar (APP)', '<b>CONFORME</b>', 'APP de {g2_app} ha ({a1_g2} m del Arroyo 1 en la punta norte) totalmente con vegetación nativa. Sin nascente ni reservorio'],
                     ['Gleba 2 ({g2_ha} ha)', 'Reserva Legal (20% = {g2_rl_ex} ha)', '<b>NO CONFORME</b> (por {g2_rl_def} ha) – condicionado', 'Necesita {g2_rl_ex} ha de vegetación nativa. La imagen muestra {g2_hoje} ha en la punta norte: faltan {g2_rl_def} ha. Si esa floresta no pertenece a la gleba (versión del cliente), faltan las {g2_rl_ex} ha enteras'],
                     ['Inmueble único ({tot_ha} ha)', 'APP + RL (variante, CAR en una matrícula)', '<b>NO CONFORME</b>', 'APP a recomponer {un_app_rec} ha (PRA-PR {un_pra} ha); RL {un_rl_ex} ha, existente {un_rl_exist} ha, déficit {un_rl_def} ha']]},
    's1_nota': {'pt': 'Diagnóstico preliminar por satélite (precisão de ±10 m no limite da vegetação; leito FBDS 2013 a 1:25.000). Os veredictos valem para a data da cena e ficam sujeitos à confirmação em campo (RTK) e à análise do IAT-PR.',
                'es': 'Diagnóstico preliminar por satélite (precisión de ±10 m en el borde de la vegetación; leito FBDS 2013 a 1:25.000). Los veredictos valen para la fecha de la escena y quedan sujetos a la confirmación en campo (RTK) y al análisis del IAT-PR.'},
    # 2. inventario
    's2_h': {'pt': 'Inventário do interior, gleba por gleba', 'es': 'Inventario del interior, gleba por gleba'},
    's2_intro': {'pt': 'Tudo o que segue foi medido dentro do perímetro de cada gleba. Os cursos d\'água são os da base oficial FBDS/IAT 2013 (1:25.000), fundidos por conectividade '
                       'para contar cursos distintos e não tramos; a vegetação é a classificação Random Forest a 10 m sobre a cena de 29/08/2026.',
                 'es': 'Todo lo que sigue se midió dentro del perímetro de cada gleba. Los cursos de agua son los de la base oficial FBDS/IAT 2013 (1:25.000), fusionados por conectividad '
                       'para contar cursos distintos y no tramos; la vegetación es la clasificación Random Forest a 10 m sobre la escena del 29/08/2026.'},
    's2_t1_h': {'pt': 'Inventário interior por gleba', 'es': 'Inventario interior por gleba'},
    's2_t1': {'pt': [['Item', 'Gleba 1 ({g1_ha} ha)', 'Gleba 2 ({g2_ha} ha)'],
                     ["Arroios (cursos d'água distintos)", '{n_arr_g1}: {km_g1} km no interior', '{n_arr_g2}: {km_g2} km no interior'],
                     ['Arroio 1 (norte) – FBDS 647524', '{a1_g1} m · atravessa', '{a1_g2} m · atravessa a ponta norte'],
                     ['Arroio 2 (central) – FBDS 647525', '{a2_g1} m · NASCE na gleba (nascente FBDS 306158) e conflui com o Arroio 1 a {conflu_m} m fora do limite oeste', '—'],
                     ['Arroio 3 (sul) – FBDS 617192 + 647547', '{a3_g1} m · atravessa; represado; {a3_per} m coincidem com IBGE "permanente"', '—'],
                     ['Nascentes', '1 FBDS (306158, perenidade a confirmar) + 2 candidatos DEM a validar (dem_1, dem_2)', 'nenhuma'],
                     ['Lagoas / represas', '1 corpo (2 massas FBDS contíguas 19083 + 20452): espelho {esp_fbds} ha (FBDS 2013) · {esp_rf} ha (RF 2026) · {esp_mndwi} ha (água clara na seca) · {esp_jrc} ha (JRC máx.)', 'nenhuma'],
                     ['Vegetação nativa (floresta RF)', '{g1_flor} ha ({g1_pct_flor}% da gleba): {g1_app_veg} ha na APP + {g1_rem} ha fora', '{g2_flor} ha ({g2_pct_flor}% da gleba): {g2_app_veg} ha na APP + {g2_rem} ha fora (ponta norte)'],
                     ['Silvicultura (RF, incerta)', '{g1_silv} ha ({g1_app_silv} ha dentro da APP)', '{g2_silv} ha'],
                     ['Água (RF)', '{g1_agua} ha', '0,00 ha'],
                     ['Área agrícola (consolidada)', '{g1_agri} ha', '{g2_agri} ha']],
              'es': [['Ítem', 'Gleba 1 ({g1_ha} ha)', 'Gleba 2 ({g2_ha} ha)'],
                     ['Arroyos (cursos de agua distintos)', '{n_arr_g1}: {km_g1} km en el interior', '{n_arr_g2}: {km_g2} km en el interior'],
                     ['Arroyo 1 (norte) – FBDS 647524', '{a1_g1} m · atraviesa', '{a1_g2} m · atraviesa la punta norte'],
                     ['Arroyo 2 (central) – FBDS 647525', '{a2_g1} m · NACE en la gleba (nascente FBDS 306158) y confluye con el Arroyo 1 a {conflu_m} m fuera del límite oeste', '—'],
                     ['Arroyo 3 (sur) – FBDS 617192 + 647547', '{a3_g1} m · atraviesa; represado; {a3_per} m coinciden con IBGE "permanente"', '—'],
                     ['Nascentes', '1 FBDS (306158, perennidad a confirmar) + 2 candidatos DEM a validar (dem_1, dem_2)', 'ninguna'],
                     ['Lagunas / represas', '1 cuerpo (2 masas FBDS contiguas 19083 + 20452): espejo {esp_fbds} ha (FBDS 2013) · {esp_rf} ha (RF 2026) · {esp_mndwi} ha (agua clara en la seca) · {esp_jrc} ha (JRC máx.)', 'ninguna'],
                     ['Vegetación nativa (floresta RF)', '{g1_flor} ha ({g1_pct_flor}% de la gleba): {g1_app_veg} ha en la APP + {g1_rem} ha fuera', '{g2_flor} ha ({g2_pct_flor}% de la gleba): {g2_app_veg} ha en la APP + {g2_rem} ha fuera (punta norte)'],
                     ['Silvicultura (RF, incierta)', '{g1_silv} ha ({g1_app_silv} ha dentro de la APP)', '{g2_silv} ha'],
                     ['Agua (RF)', '{g1_agua} ha', '0,00 ha'],
                     ['Área agrícola (consolidada)', '{g1_agri} ha', '{g2_agri} ha']]},
    's2_nota': {'pt': 'Critério de "curso distinto": fusão topológica dos tramos FBDS completos (nós de grau 2 unidos); uma confluência separa afluente de curso principal. '
                      'Os Arroios 1 e 2 confluem fora do imóvel: são dois cursos. O Arroio 3 é um só curso (dois ids FBDS em sequência). '
                      'O reservatório: as duas massas FBDS são contíguas e formam UM corpo; na seca de 2026 a água clara mede {esp_mndwi} ha, mas a cota normal excede 1 ha em três medidas, por isso não se presume a dispensa do art. 4º §4º.',
                'es': 'Criterio de "curso distinto": fusión topológica de los tramos FBDS completos (nodos de grado 2 unidos); una confluencia separa afluente de curso principal. '
                      'Los Arroyos 1 y 2 confluyen fuera del inmueble: son dos cursos. El Arroyo 3 es un solo curso (dos ids FBDS en secuencia). '
                      'El reservorio: las dos masas FBDS son contiguas y forman UN cuerpo; en la seca de 2026 el agua clara mide {esp_mndwi} ha, pero la cota normal supera 1 ha en tres medidas, por eso no se presume la dispensa del art. 4º §4º.'},
    'v01_cap': {'pt': 'Mapa V01 – Vegetação nativa no interior do imóvel, com os fragmentos e a área por gleba.', 'es': 'Mapa V01 – Vegetación nativa en el interior del inmueble, con los fragmentos y el área por gleba.'},
    'v02_cap': {'pt': 'Mapa V02 – Hidrografia interior: arroios numerados com o comprimento por gleba, nascente, candidatos DEM e reservatório.', 'es': 'Mapa V02 – Hidrografía interior: arroyos numerados con la longitud por gleba, nascente, candidatos DEM y reservorio.'},
    # 3. APP
    's3_h': {'pt': 'Mata ciliar (APP): exigida, com vegetação e a recompor', 'es': 'Mata ciliar (APP): exigida, con vegetación y a recomponer'},
    's3_base_h': {'pt': 'Base legal em seis linhas', 'es': 'Base legal en seis líneas'},
    's3_base': {'pt': ['<b>Art. 4º I da Lei 12.651/2012</b>: faixa de 30 m em cada margem dos cursos d\'água de menos de 10 m, medida da borda da calha do leito regular (perenes e intermitentes; efêmeros excluídos).',
                       '<b>Art. 4º IV</b>: raio de 50 m ao redor das nascentes (o STF, ADI 4903, estendeu às intermitentes).',
                       '<b>Art. 4º III</b>: reservatório artificial por barramento de curso natural tem a faixa definida na licença ambiental; o §4º dispensa a faixa se o espelho é menor que 1 ha – aqui não se presume.',
                       '<b>Art. 61-A</b> (área consolidada até 22/07/2008) com a <b>Lei PR 18.295/2014 art. 17 §2º</b> (4 a 10 MF): recomposição reduzida a 20 m nos cursos e raio de 15 m nas nascentes, condicionada a CAR até 31/12/2023 e adesão ao PRA.',
                       '<b>STF 28/02/2018</b> (ADI 4901-4903, 4937; ADC 42): validou o regime das áreas consolidadas e o cômputo da APP na RL.',
                       '<b>Cenário FBDS/IAT</b>: a camada oficial app_hidrica do IAT mapeia 30 m ao redor do espelho do reservatório; reportado como cenário, não somado ao exigível base.'],
                'es': ['<b>Art. 4º I de la Ley 12.651/2012</b>: faja de 30 m en cada margen de los cursos de agua de menos de 10 m, medida desde el borde del cauce del leito regular (perennes e intermitentes; efímeros excluidos).',
                       '<b>Art. 4º IV</b>: radio de 50 m alrededor de las nascentes (el STF, ADI 4903, lo extendió a las intermitentes).',
                       '<b>Art. 4º III</b>: el reservorio artificial por represamiento de curso natural tiene la faja definida en la licencia ambiental; el §4º dispensa la faja si el espejo es menor que 1 ha – aquí no se presume.',
                       '<b>Art. 61-A</b> (área consolidada hasta el 22/07/2008) con la <b>Ley PR 18.295/2014 art. 17 §2º</b> (4 a 10 MF): recomposición reducida a 20 m en los cursos y radio de 15 m en las nascentes, condicionada a CAR hasta el 31/12/2023 y adhesión al PRA.',
                       '<b>STF 28/02/2018</b> (ADI 4901-4903, 4937; ADC 42): validó el régimen de las áreas consolidadas y el cómputo de la APP en la RL.',
                       '<b>Escenario FBDS/IAT</b>: la capa oficial app_hidrica del IAT mapea 30 m alrededor del espejo del reservorio; reportado como escenario, no sumado a lo exigible base.']},
    's3_t1_h': {'pt': 'APP por gleba (ha)', 'es': 'APP por gleba (ha)'},
    's3_t1': {'pt': [['APP', 'Gleba 1', 'Gleba 2', 'Imóvel único'],
                     ['Exigida (30 m cursos + 50 m nascente)', '{g1_app}', '{g2_app}', '{un_app}'],
                     ['   sendo curso d\'água / nascente', '{g1_app_curso} / {g1_app_nasc}', '{g2_app} / 0,00', '{un_app_curso} / {un_app_nasc}'],
                     ['Com vegetação nativa (conforme)', '{g1_app_veg} ({g1_pct}%)', '{g2_app_veg} ({g2_pct}%)', '{un_app_veg} ({un_pct}%)'],
                     ['Com água (espelho do reservatório)', '{g1_app_agua}', '0,00', '{un_app_agua}'],
                     ['<b>A recompor – cenário integral</b>', '<b>{g1_app_rec}</b>', '<b>{g2_app_rec}</b>', '<b>{un_app_rec}</b>'],
                     ['   dos quais silvicultura (substituir)', '{g1_app_silv}', '0,00', '{un_app_silv}'],
                     ['A recompor – cenário PRA-PR (20 m / 15 m)', '{g1_pra}', '0,00', '{un_pra}'],
                     ['Exigida – cenário FBDS/IAT (+ faixa 30 m do reservatório)', '{g1_appF}', '{g2_app}', '{un_appF}'],
                     ['A recompor – cenário FBDS/IAT', '{g1_appF_rec}', '0,00', '{un_appF_rec}'],
                     ['<b>Veredito</b>', '<b>NÃO CONFORME</b>', '<b>CONFORME</b>', '<b>NÃO CONFORME</b>']],
              'es': [['APP', 'Gleba 1', 'Gleba 2', 'Inmueble único'],
                     ['Exigida (30 m cursos + 50 m nascente)', '{g1_app}', '{g2_app}', '{un_app}'],
                     ['   de la cual curso de agua / nascente', '{g1_app_curso} / {g1_app_nasc}', '{g2_app} / 0,00', '{un_app_curso} / {un_app_nasc}'],
                     ['Con vegetación nativa (conforme)', '{g1_app_veg} ({g1_pct}%)', '{g2_app_veg} ({g2_pct}%)', '{un_app_veg} ({un_pct}%)'],
                     ['Con agua (espejo del reservorio)', '{g1_app_agua}', '0,00', '{un_app_agua}'],
                     ['<b>A recomponer – escenario integral</b>', '<b>{g1_app_rec}</b>', '<b>{g2_app_rec}</b>', '<b>{un_app_rec}</b>'],
                     ['   de los cuales silvicultura (sustituir)', '{g1_app_silv}', '0,00', '{un_app_silv}'],
                     ['A recomponer – escenario PRA-PR (20 m / 15 m)', '{g1_pra}', '0,00', '{un_pra}'],
                     ['Exigida – escenario FBDS/IAT (+ faja 30 m del reservorio)', '{g1_appF}', '{g2_app}', '{un_appF}'],
                     ['A recomponer – escenario FBDS/IAT', '{g1_appF_rec}', '0,00', '{un_appF_rec}'],
                     ['<b>Veredicto</b>', '<b>NO CONFORME</b>', '<b>CONFORME</b>', '<b>NO CONFORME</b>']]},
    's3_nota': {'pt': 'Onde falta mata ciliar na Gleba 1: a faixa do Arroio 2 entre a nascente e a divisa oeste (lavoura encostada no curso) e as duas margens do Arroio 3 ao redor do reservatório. '
                      'A supressão pós-2008 confirmada é de {supr08} ha: quase toda a APP sem vegetação é área consolidada e cabe no art. 61-A. '
                      'Riscos não somados: se os candidatos DEM a nascente forem confirmados, +{cand_add} ha de APP; se houver curso intermitente no talvegue dem_2 (em soja), +{talv} ha.',
                'es': 'Dónde falta mata ciliar en la Gleba 1: la faja del Arroyo 2 entre la nascente y el lindero oeste (cultivo pegado al curso) y las dos márgenes del Arroyo 3 alrededor del reservorio. '
                      'La supresión pos-2008 confirmada es de {supr08} ha: casi toda la APP sin vegetación es área consolidada y cabe en el art. 61-A. '
                      'Riesgos no sumados: si los candidatos DEM a nascente se confirman, +{cand_add} ha de APP; si hay curso intermitente en el talweg dem_2 (en soja), +{talv} ha.'},
    'v03_cap': {'pt': 'Mapa V03 – APP por gleba: conforme (verde), água (azul), a recompor (vermelho; laranja = silvicultura), faixa PRA-PR (magenta) e faixa do reservatório (hachura).',
                'es': 'Mapa V03 – APP por gleba: conforme (verde), agua (azul), a recomponer (rojo; naranja = silvicultura), faja PRA-PR (magenta) y faja del reservorio (rayado).'},
    # 4. RL
    's4_h': {'pt': 'Reserva Legal: exigida, existente e déficit', 'es': 'Reserva Legal: exigida, existente y déficit'},
    's4_base': {'pt': '<b>Art. 12 II</b>: 20% da área do imóvel fora da Amazônia Legal. <b>Art. 15</b>: a APP conservada ou em recuperação computa na RL se o CAR estiver inscrito e não houver conversão de novas áreas. '
                      '<b>Art. 66</b>: o déficit se regulariza por recomposição (até 20 anos, 1/10 a cada 2 anos), regeneração natural ou compensação no mesmo bioma (IN IAT 53/2025). '
                      '<b>Art. 14</b>: a localização é aprovada pelo IAT. RL calculada sobre a área de cada gleba sem descontar servidões (sem dado; IN MMA 2/2014 art. 23 I).',
                'es': '<b>Art. 12 II</b>: 20% del área del inmueble fuera de la Amazonía Legal. <b>Art. 15</b>: la APP conservada o en recuperación computa en la RL si el CAR está inscrito y no hay conversión de nuevas áreas. '
                      '<b>Art. 66</b>: el déficit se regulariza por recomposición (hasta 20 años, 1/10 cada 2 años), regeneración natural o compensación en el mismo bioma (IN IAT 53/2025). '
                      '<b>Art. 14</b>: la localización la aprueba el IAT. RL calculada sobre el área de cada gleba sin descontar servidumbres (sin dato; IN MMA 2/2014 art. 23 I).'},
    's4_t1_h': {'pt': 'Reserva Legal por gleba (ha)', 'es': 'Reserva Legal por gleba (ha)'},
    's4_t1': {'pt': [['Reserva Legal', 'Gleba 1', 'Gleba 2', 'Imóvel único'],
                     ['Área da gleba', '{g1_ha}', '{g2_ha}', '{tot_ha}'],
                     ['<b>Exigida (20%)</b>', '<b>{g1_rl_ex}</b>', '<b>{g2_rl_ex}</b>', '<b>{un_rl_ex}</b>'],
                     ['Remanescente fora da APP', '{g1_rem}', '{g2_rem}', '{un_rem}'],
                     ['APP com vegetação nativa (art. 15)', '{g1_app_veg}', '{g2_app_veg}', '{un_app_veg}'],
                     ['<b>Existente (remanescente + APP vegetada)</b>', '<b>{g1_rl_exist}</b>', '<b>{g2_rl_exist}</b>', '<b>{un_rl_exist}</b>'],
                     ['Existente sem computar a APP', '{g1_rem}', '{g2_rem}', '{un_rem}'],
                     ['<b>Déficit (com APP, art. 15)</b>', '<b>{g1_rl_def}</b>', '<b>{g2_rl_def}</b>', '<b>{un_rl_def}</b>'],
                     ['Déficit sem computar a APP', '{g1_rl_def_sem}', '{g2_rl_def_sem}', '{un_rl_def_sem}'],
                     ['Atendimento', '{g1_rl_pct}%', '{g2_rl_pct}%', '{un_rl_pct}%'],
                     ['<b>Veredito</b>', '<b>NÃO CONFORME</b>', '<b>NÃO CONFORME</b> (condicionado)', '<b>NÃO CONFORME</b>']],
              'es': [['Reserva Legal', 'Gleba 1', 'Gleba 2', 'Inmueble único'],
                     ['Área de la gleba', '{g1_ha}', '{g2_ha}', '{tot_ha}'],
                     ['<b>Exigida (20%)</b>', '<b>{g1_rl_ex}</b>', '<b>{g2_rl_ex}</b>', '<b>{un_rl_ex}</b>'],
                     ['Remanente fuera de la APP', '{g1_rem}', '{g2_rem}', '{un_rem}'],
                     ['APP con vegetación nativa (art. 15)', '{g1_app_veg}', '{g2_app_veg}', '{un_app_veg}'],
                     ['<b>Existente (remanente + APP vegetada)</b>', '<b>{g1_rl_exist}</b>', '<b>{g2_rl_exist}</b>', '<b>{un_rl_exist}</b>'],
                     ['Existente sin computar la APP', '{g1_rem}', '{g2_rem}', '{un_rem}'],
                     ['<b>Déficit (con APP, art. 15)</b>', '<b>{g1_rl_def}</b>', '<b>{g2_rl_def}</b>', '<b>{un_rl_def}</b>'],
                     ['Déficit sin computar la APP', '{g1_rl_def_sem}', '{g2_rl_def_sem}', '{un_rl_def_sem}'],
                     ['Cumplimiento', '{g1_rl_pct}%', '{g2_rl_pct}%', '{un_rl_pct}%'],
                     ['<b>Veredicto</b>', '<b>NO CONFORME</b>', '<b>NO CONFORME</b> (condicionado)', '<b>NO CONFORME</b>']]},
    'g2_lbl': {'pt': 'Gleba 2 – os 6 alqueires', 'es': 'Gleba 2 – los 6 alqueires'},
    'g2_call': {'pt': 'Para estar na lei, a Gleba 2 precisa de {g2_rl_ex} ha de vegetação nativa (RL de 20% sobre {g2_ha} ha); a APP própria ({g2_app} ha, já vegetada) computa dentro desses {g2_rl_ex} ha pelo art. 15 – sem esse cômputo seriam {g2_min_sem} ha. '
                      'Hoje a imagem mostra {g2_hoje} ha de floresta na ponta norte da gleba (continuação do fragmento 2, mata do vizinho, floresta desde 1985): faltariam só {g2_rl_def} ha. '
                      'O cliente afirma que a compra dos 6 alqueires não incluía monte: é preciso confirmar em campo e na escritura se essa floresta pertence à gleba. Se não pertencer, os {g2_rl_ex} ha ficam integralmente a recompor, regenerar ou compensar (art. 66).',
                'es': 'Para estar en la ley, la Gleba 2 necesita {g2_rl_ex} ha de vegetación nativa (RL del 20% sobre {g2_ha} ha); la APP propia ({g2_app} ha, ya vegetada) computa dentro de esas {g2_rl_ex} ha por el art. 15 – sin ese cómputo serían {g2_min_sem} ha. '
                      'Hoy la imagen muestra {g2_hoje} ha de floresta en la punta norte de la gleba (continuación del fragmento 2, monte del vecino, floresta desde 1985): faltarían solo {g2_rl_def} ha. '
                      'El cliente afirma que la compra de los 6 alqueires no incluía monte: hay que confirmar en campo y en la escritura si esa floresta pertenece a la gleba. Si no pertenece, las {g2_rl_ex} ha quedan íntegramente a recomponer, regenerar o compensar (art. 66).'},
    's4_prop_h': {'pt': 'Reserva Legal proposta, recortada à Gleba 1', 'es': 'Reserva Legal propuesta, recortada a la Gleba 1'},
    's4_prop': {'pt': 'A proposta de localização elaborada para o imóvel único ({rl_prop_tot} ha em 5 blocos) foi recortada ao polígono da Gleba 1: restam <b>{rl_prop_g1} ha</b> (remanescente + APP vegetada + APP a recompor incluída + corredor de recomposição de {corr_g1} ha), '
                      '<b>{rl_prop_falta} ha aquém</b> dos {g1_rl_ex} ha exigidos. Os {rl_prop_g2} ha que a proposta original apoiava na Gleba 2 não podem mais contar para a Gleba 1: o corredor deve ser ampliado dentro da Gleba 1 (contíguo à mata do Arroio 2 ou ao reservatório) ou o saldo compensado (art. 66 III).',
                'es': 'La propuesta de localización elaborada para el inmueble único ({rl_prop_tot} ha en 5 bloques) se recortó al polígono de la Gleba 1: quedan <b>{rl_prop_g1} ha</b> (remanente + APP vegetada + APP a recomponer incluida + corredor de recomposición de {corr_g1} ha), '
                      '<b>{rl_prop_falta} ha por debajo</b> de las {g1_rl_ex} ha exigidas. Las {rl_prop_g2} ha que la propuesta original apoyaba en la Gleba 2 ya no pueden contar para la Gleba 1: el corredor debe ampliarse dentro de la Gleba 1 (contiguo al monte del Arroyo 2 o al reservorio) o el saldo compensarse (art. 66 III).'},
    'v04_cap': {'pt': 'Mapa V04 – Reserva Legal existente por gleba (remanescente + APP vegetada), corredor proposto e RL proposta recortada à Gleba 1.',
                'es': 'Mapa V04 – Reserva Legal existente por gleba (remanente + APP vegetada), corredor propuesto y RL propuesta recortada a la Gleba 1.'},
    'v06_cap': {'pt': 'Mapa V06 – Detalhe da Gleba 2: floresta da ponta norte, APP do Arroio 1 e a conta da Reserva Legal própria.',
                'es': 'Mapa V06 – Detalle de la Gleba 2: floresta de la punta norte, APP del Arroyo 1 y la cuenta de la Reserva Legal propia.'},
    # 5. CAR
    's5_h': {'pt': 'Mapa de uso e cobertura com a nomenclatura CAR/SICAR', 'es': 'Mapa de uso y cobertura con la nomenclatura CAR/SICAR'},
    's5_intro': {'pt': 'Polígonos sem sobreposição com as classes do Módulo de Cadastro (IN MMA 2/2014). Cada gleba fecha na sua área: Gleba 1 em {g1_car_soma} ha e Gleba 2 em {g2_car_soma} ha ({tot_ha} ha no total). '
                       'A camada está pronta para o SICAR em SIRGAS 2000 (04_VETORES_ENTREGA_V2).',
                 'es': 'Polígonos sin superposición con las clases del Módulo de Catastro (IN MMA 2/2014). Cada gleba cierra en su área: Gleba 1 en {g1_car_soma} ha y Gleba 2 en {g2_car_soma} ha ({tot_ha} ha en total). '
                       'La capa está lista para el SICAR en SIRGAS 2000 (04_VETORES_ENTREGA_V2).'},
    's5_t1': {'pt': ['Classe CAR', 'Subclasse', 'Gleba 1 (ha)', 'Gleba 2 (ha)', 'Total (ha)'], 'es': ['Clase CAR', 'Subclase', 'Gleba 1 (ha)', 'Gleba 2 (ha)', 'Total (ha)']},
    'car_sub': {'pt': {'conforme': 'conforme', 'a recompor': 'a recompor', 'espelho d agua': "espelho d'água", 'floresta fora da APP': 'floresta fora da APP', 'uso agricola': 'uso agrícola', 'silvicultura': 'silvicultura'},
                'es': {'conforme': 'conforme', 'a recompor': 'a recomponer', 'espelho d agua': 'espejo de agua', 'floresta fora da APP': 'floresta fuera de la APP', 'uso agricola': 'uso agrícola', 'silvicultura': 'silvicultura'}},
    'soma': {'pt': 'Soma', 'es': 'Suma'},
    'v05_cap': {'pt': 'Mapa V05 – Uso e cobertura com nomenclatura CAR/SICAR, por gleba.', 'es': 'Mapa V05 – Uso y cobertura con nomenclatura CAR/SICAR, por gleba.'},
    # 6. metodo
    's6_h': {'pt': 'Método, precisão e limitações', 'es': 'Método, precisión y limitaciones'},
    's6_met': {'pt': ['<b>Imagem</b>: Sentinel-2C L2A de 29/08/2026 (10 m), sem nuvens sobre o imóvel; classificação Random Forest em quatro classes (floresta nativa, água, área antropizada, silvicultura), exatidão global {oa} e kappa {kappa} medidas por blocos espaciais sobre píxeis de consenso de três produtos globais (não verdade de campo); silvicultura com F1 {f1_silv} (incerta).',
                      '<b>Hidrografia</b>: base oficial FBDS/IAT 2013 (RapidEye 5 m, 1:25.000) como leito de referência; a rede DEM GLO-30 (mediana {med_dem} m, P90 {p90_dem} m de distância) e as bases otto/ANA/IBGE só como controle. A APP foi medida do eixo da linha FBDS; a borda da calha exige RTK.',
                      '<b>Precisão</b>: ±10 m (1 píxel) no limite da vegetação; a APP integral do imóvel varia entre {app_min} e {app_max} ha conforme a posição do leito; a floresta entre {flor_min} e {flor_max} ha (borda de 1 píxel).',
                      '<b>Série NDVI</b> de 24 meses: o fragmento 13 (faixa ciliar norte) mantém NDVI {f13_min}-{f13_max} o ano todo, sem a queda de entressafra das lavouras: vegetação permanente, não cultivo anual.',
                      '<b>Glebas</b>: os polígonos do GeoJSON do cliente (EPSG:31982) não se tocam ({dist_glebas} m); tudo foi calculado sobre a união e depois recortado a cada gleba, e a soma G1 + G2 reproduz os totais auditados do imóvel com diferença máxima de 0,01 ha (arredondamento).'],
               'es': ['<b>Imagen</b>: Sentinel-2C L2A del 29/08/2026 (10 m), sin nubes sobre el inmueble; clasificación Random Forest en cuatro clases (floresta nativa, agua, área antropizada, silvicultura), exactitud global {oa} y kappa {kappa} medidas por bloques espaciales sobre píxeles de consenso de tres productos globales (no verdad de campo); silvicultura con F1 {f1_silv} (incierta).',
                      '<b>Hidrografía</b>: base oficial FBDS/IAT 2013 (RapidEye 5 m, 1:25.000) como leito de referencia; la red DEM GLO-30 (mediana {med_dem} m, P90 {p90_dem} m de distancia) y las bases otto/ANA/IBGE solo como control. La APP se midió desde el eje de la línea FBDS; el borde del cauce exige RTK.',
                      '<b>Precisión</b>: ±10 m (1 píxel) en el borde de la vegetación; la APP integral del inmueble varía entre {app_min} y {app_max} ha según la posición del leito; la floresta entre {flor_min} y {flor_max} ha (borde de 1 píxel).',
                      '<b>Serie NDVI</b> de 24 meses: el fragmento 13 (faja ribereña norte) mantiene NDVI {f13_min}-{f13_max} todo el año, sin la caída de entrezafra de los cultivos: vegetación permanente, no cultivo anual.',
                      '<b>Glebas</b>: los polígonos del GeoJSON del cliente (EPSG:31982) no se tocan ({dist_glebas} m); todo se calculó sobre la unión y luego se recortó a cada gleba, y la suma G1 + G2 reproduce los totales auditados del inmueble con diferencia máxima de 0,01 ha (redondeo).']},
    'alcance_lbl': {'pt': 'Alcance', 'es': 'Alcance'},
    'alcance': {'pt': 'O presente diagnóstico satelital é <b>preliminar</b>; delimita cobertura vegetal com precisão de ±10 m e utiliza a hidrografia oficial FBDS/IAT (2013, 1:25.000) como referência do leito regular. '
                      'Não constitui laudo com validade legal: o CAR é declaratório (Lei 12.651/2012, art. 29) e sua validação pelo IAT-PR segue a IN IAT 05/2023; a posição do leito regular e a perenidade das nascentes devem ser confirmadas em campo (GPS RTK) antes de qualquer uso administrativo.',
                'es': 'El presente diagnóstico satelital es <b>preliminar</b>; delimita cobertura vegetal con precisión de ±10 m y utiliza la hidrografía oficial FBDS/IAT (2013, 1:25.000) como referencia del leito regular. '
                      'No constituye un laudo con validez legal: el CAR es declaratorio (Ley 12.651/2012, art. 29) y su validación por el IAT-PR sigue la IN IAT 05/2023; la posición del leito regular y la perennidad de las nascentes deben confirmarse en campo (GPS RTK) antes de cualquier uso administrativo.'},
    's6_lim_h': {'pt': 'Limitações e próximos passos', 'es': 'Limitaciones y próximos pasos'},
    's6_lim': {'pt': ['<b>Levantamento RTK</b> da borda da calha dos três arroios e da nascente 306158 (estação seca, pontos a cada 20-30 m): fixa a APP com precisão de decímetros e tem valor probatório.',
                      '<b>Nascente candidata dem_2</b> (em soja, sem curso em nenhuma base) e talvegue de 700 m: verificar na estação chuvosa; se houver curso intermitente, a APP da Gleba 1 cresce até {talv} ha.',
                      '<b>Sobreposição de CAR</b>: um imóvel vizinho (PR-4124301-F127CD1E...) declara um reservatório de {car_viz} ha 100% dentro da Gleba 1 – verificar no SICAR antes de inscrever ou retificar.',
                      '<b>Data do CAR</b>: a faixa reduzida do PRA-PR ({g1_pra} ha) só vale com CAR inscrito até 31/12/2023 e adesão ao PRA; sem isso vale o cenário integral ({g1_app_rec} ha).',
                      '<b>Gleba 2</b>: confirmar em campo e na matrícula se a floresta da ponta norte ({g2_hoje} ha) pertence à gleba; a resposta muda o déficit de {g2_rl_def} ha para {g2_rl_ex} ha.',
                      '<b>Estágio sucessional</b> dos fragmentos (CONAMA 2/1994: DAP, área basal, estratos) e natureza do fragmento 13 (regeneração vs plantio): inventário de campo obrigatório.',
                      '<b>Faixa do reservatório</b>: depende da licença (art. 4º III; IN IAT 64/2025); o cenário FBDS/IAT (+{g1_appF_add} ha) mostra o que mudaria.'],
               'es': ['<b>Levantamiento RTK</b> del borde del cauce de los tres arroyos y de la nascente 306158 (estación seca, puntos cada 20-30 m): fija la APP con precisión de decímetros y tiene valor probatorio.',
                      '<b>Nascente candidata dem_2</b> (en soja, sin curso en ninguna base) y talweg de 700 m: verificar en la estación lluviosa; si hay curso intermitente, la APP de la Gleba 1 crece hasta {talv} ha.',
                      '<b>Superposición de CAR</b>: un inmueble vecino (PR-4124301-F127CD1E...) declara un reservorio de {car_viz} ha 100% dentro de la Gleba 1 – verificar en el SICAR antes de inscribir o rectificar.',
                      '<b>Fecha del CAR</b>: la faja reducida del PRA-PR ({g1_pra} ha) solo vale con CAR inscrito hasta el 31/12/2023 y adhesión al PRA; sin eso vale el escenario integral ({g1_app_rec} ha).',
                      '<b>Gleba 2</b>: confirmar en campo y en la matrícula si la floresta de la punta norte ({g2_hoje} ha) pertenece a la gleba; la respuesta cambia el déficit de {g2_rl_def} ha a {g2_rl_ex} ha.',
                      '<b>Estadio sucesional</b> de los fragmentos (CONAMA 2/1994: DAP, área basal, estratos) y naturaleza del fragmento 13 (regeneración vs plantación): inventario de campo obligatorio.',
                      '<b>Faja del reservorio</b>: depende de la licencia (art. 4º III; IN IAT 64/2025); el escenario FBDS/IAT (+{g1_appF_add} ha) muestra lo que cambiaría.']},
    # anexo
    'anexo_h': {'pt': 'Anexo: fontes legais e arquivos entregues', 'es': 'Anexo: fuentes legales y archivos entregados'},
    'anexo_leg_h': {'pt': 'Fontes legais consultadas (06/09/2026)', 'es': 'Fuentes legales consultadas (06/09/2026)'},
    'anexo_leg': {'pt': [['Norma', 'Conteúdo usado', 'URL'],
                         ['Lei 12.651/2012 (Código Florestal)', 'arts. 3º, 4º, 12, 14, 15, 29, 61-A, 66', 'planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/L12651compilado.htm'],
                         ['Lei 11.428/2006 e Decreto 6.660/2008', 'Mata Atlântica: estágios e supressão', 'planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11428.htm'],
                         ['Decreto 7.830/2012 · IN MMA 2/2014', 'SICAR; camadas do CAR; datum SIRGAS 2000; RL sem servidões', 'planalto.gov.br (d7830.htm) · car.gov.br/leis/IN_CAR.pdf'],
                         ['Resolução CONAMA 2/1994', 'estágios sucessionais no Paraná', 'snif.florestal.gov.br (resolucao_conama_02_1994.pdf)'],
                         ['Lei PR 18.295/2014 · Decreto PR 11.515/2018', 'PRA-PR; art. 17 §2º-§3º (20 m / 15 m); prazos', 'legislacao.pr.gov.br (codAto=132558; codAto=209637)'],
                         ['IN IAT 53/2025 · IN IAT 64/2025', 'compensação de RL; APP de reservatórios', 'iat.pr.gov.br · legisweb.com.br/legislacao/?id=486372'],
                         ['STF 28/02/2018 (ADI 4901-4903, 4937; ADC 42)', 'nascentes intermitentes; área consolidada; APP na RL', 'portal.stf.jus.br (casos_notorios_2018)'],
                         ['INCRA/SNCR 2005 · Embrapa · IBGE 2024', 'módulo fiscal 20 ha; bioma Mata Atlântica', 'sistemafaep.org.br · embrapa.br/codigo-florestal · geoftp.ibge.gov.br']],
                  'es': [['Norma', 'Contenido usado', 'URL'],
                         ['Ley 12.651/2012 (Código Forestal)', 'arts. 3º, 4º, 12, 14, 15, 29, 61-A, 66', 'planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/L12651compilado.htm'],
                         ['Ley 11.428/2006 y Decreto 6.660/2008', 'Mata Atlántica: estadios y supresión', 'planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11428.htm'],
                         ['Decreto 7.830/2012 · IN MMA 2/2014', 'SICAR; capas del CAR; datum SIRGAS 2000; RL sin servidumbres', 'planalto.gov.br (d7830.htm) · car.gov.br/leis/IN_CAR.pdf'],
                         ['Resolución CONAMA 2/1994', 'estadios sucesionales en Paraná', 'snif.florestal.gov.br (resolucao_conama_02_1994.pdf)'],
                         ['Ley PR 18.295/2014 · Decreto PR 11.515/2018', 'PRA-PR; art. 17 §2º-§3º (20 m / 15 m); plazos', 'legislacao.pr.gov.br (codAto=132558; codAto=209637)'],
                         ['IN IAT 53/2025 · IN IAT 64/2025', 'compensación de RL; APP de reservorios', 'iat.pr.gov.br · legisweb.com.br/legislacao/?id=486372'],
                         ['STF 28/02/2018 (ADI 4901-4903, 4937; ADC 42)', 'nascentes intermitentes; área consolidada; APP en la RL', 'portal.stf.jus.br (casos_notorios_2018)'],
                         ['INCRA/SNCR 2005 · Embrapa · IBGE 2024', 'módulo fiscal 20 ha; bioma Mata Atlántica', 'sistemafaep.org.br · embrapa.br/codigo-florestal · geoftp.ibge.gov.br']]},
    'anexo_arq_h': {'pt': 'Arquivos entregues', 'es': 'Archivos entregados'},
    'anexo_arq': {'pt': [['Pasta / arquivo', 'Conteúdo'],
                         ['04_VETORES_ENTREGA_V2/gleba_limites.*', 'as duas glebas com área, alqueires e RL exigida'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_car.* · gleba_G2_car.*', 'uso e cobertura CAR/SICAR por gleba (fecham em {g1_ha} e {g2_ha} ha)'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_app.* · gleba_G2_app.*', 'APP por feição e situação (conforme / a recompor / água), com a faixa PRA-PR e o cenário FBDS/IAT'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_rl_existente.* · gleba_G2_rl_existente.*', 'RL existente (remanescente + APP vegetada) com exigida e déficit por gleba'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_arroios.* · gleba_G2_arroios.*', 'arroios numerados com comprimento dentro da gleba, tipo e ids FBDS'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_lagoas.* · gleba_G*_floresta.* · RL_proposta_G1.* · LEIAME.txt', 'reservatório e fragmentos por gleba; RL proposta recortada à Gleba 1 ({rl_prop_g1} ha); descrição bilíngue dos campos'],
                         ['03_MAPAS_V2/V01-V06 (.png; ES/)', 'mapas do interior do perímetro, A4 vertical (250 dpi), PT e ES'],
                         ['02_ANALISIS/resultados_glebas.json', 'todas as cifras deste dictame por gleba e a verificação G1 + G2 vs imóvel']],
                  'es': [['Carpeta / archivo', 'Contenido'],
                         ['04_VETORES_ENTREGA_V2/gleba_limites.*', 'las dos glebas con área, alqueires y RL exigida'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_car.* · gleba_G2_car.*', 'uso y cobertura CAR/SICAR por gleba (cierran en {g1_ha} y {g2_ha} ha)'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_app.* · gleba_G2_app.*', 'APP por rasgo y situación (conforme / a recomponer / agua), con la faja PRA-PR y el escenario FBDS/IAT'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_rl_existente.* · gleba_G2_rl_existente.*', 'RL existente (remanente + APP vegetada) con exigida y déficit por gleba'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_arroios.* · gleba_G2_arroios.*', 'arroyos numerados con longitud dentro de la gleba, tipo e ids FBDS'],
                         ['04_VETORES_ENTREGA_V2/gleba_G1_lagoas.* · gleba_G*_floresta.* · RL_proposta_G1.* · LEIAME.txt', 'reservorio y fragmentos por gleba; RL propuesta recortada a la Gleba 1 ({rl_prop_g1} ha); descripción bilingüe de los campos'],
                         ['03_MAPAS_V2/V01-V06 (.png; ES/)', 'mapas del interior del perímetro, A4 vertical (250 dpi), PT y ES'],
                         ['02_ANALISIS/resultados_glebas.json', 'todas las cifras de este dictamen por gleba y la verificación G1 + G2 vs inmueble']]},
}
